// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	servicesv1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	mock "github.com/stretchr/testify/mock"
)

// MockRoleService is an autogenerated mock type for the RoleService type
type MockRoleService struct {
	mock.Mock
}

// CreateRole provides a mock function with given fields: ctx, req
func (_m *MockRoleService) CreateRole(ctx context.Context, req *servicesv1.CreateRoleRequest) (*servicesv1.CreateRoleResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *servicesv1.CreateRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *servicesv1.CreateRoleRequest) (*servicesv1.CreateRoleResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *servicesv1.CreateRoleRequest) *servicesv1.CreateRoleResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.CreateRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *servicesv1.CreateRoleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRole provides a mock function with given fields: ctx, uuid
func (_m *MockRoleService) DeleteRole(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRole provides a mock function with given fields: ctx, uuid
func (_m *MockRoleService) GetRole(ctx context.Context, uuid string) (*servicesv1.GetRoleResponse, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *servicesv1.GetRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*servicesv1.GetRoleResponse, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *servicesv1.GetRoleResponse); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.GetRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRoles provides a mock function with given fields: ctx, count
func (_m *MockRoleService) ListRoles(ctx context.Context, count int32) (*servicesv1.ListRolesResponse, error) {
	ret := _m.Called(ctx, count)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 *servicesv1.ListRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*servicesv1.ListRolesResponse, error)); ok {
		return rf(ctx, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *servicesv1.ListRolesResponse); ok {
		r0 = rf(ctx, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.ListRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRole provides a mock function with given fields: ctx, uuid, req
func (_m *MockRoleService) UpdateRole(ctx context.Context, uuid string, req *servicesv1.UpdateRoleRequest) (*servicesv1.UpdateRoleResponse, error) {
	ret := _m.Called(ctx, uuid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 *servicesv1.UpdateRoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *servicesv1.UpdateRoleRequest) (*servicesv1.UpdateRoleResponse, error)); ok {
		return rf(ctx, uuid, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *servicesv1.UpdateRoleRequest) *servicesv1.UpdateRoleResponse); ok {
		r0 = rf(ctx, uuid, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.UpdateRoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *servicesv1.UpdateRoleRequest) error); ok {
		r1 = rf(ctx, uuid, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRoleService creates a new instance of MockRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	mock := &MockRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
