// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	servicesv1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	mock "github.com/stretchr/testify/mock"
)

// MockConversationService is an autogenerated mock type for the ConversationService type
type MockConversationService struct {
	mock.Mock
}

// CreateConversation provides a mock function with given fields: ctx, req
func (_m *MockConversationService) CreateConversation(ctx context.Context, req *servicesv1.CreateConversationRequest) (*servicesv1.CreateConversationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 *servicesv1.CreateConversationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *servicesv1.CreateConversationRequest) (*servicesv1.CreateConversationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *servicesv1.CreateConversationRequest) *servicesv1.CreateConversationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.CreateConversationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *servicesv1.CreateConversationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConversation provides a mock function with given fields: ctx, uuid
func (_m *MockConversationService) DeleteConversation(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConversation provides a mock function with given fields: ctx, uuid
func (_m *MockConversationService) GetConversation(ctx context.Context, uuid string) (*servicesv1.GetConversationResponse, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 *servicesv1.GetConversationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*servicesv1.GetConversationResponse, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *servicesv1.GetConversationResponse); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.GetConversationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConversations provides a mock function with given fields: ctx, count
func (_m *MockConversationService) ListConversations(ctx context.Context, count int32) (*servicesv1.ListConversationsResponse, error) {
	ret := _m.Called(ctx, count)

	if len(ret) == 0 {
		panic("no return value specified for ListConversations")
	}

	var r0 *servicesv1.ListConversationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*servicesv1.ListConversationsResponse, error)); ok {
		return rf(ctx, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *servicesv1.ListConversationsResponse); ok {
		r0 = rf(ctx, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.ListConversationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConversation provides a mock function with given fields: ctx, uuid, req
func (_m *MockConversationService) UpdateConversation(ctx context.Context, uuid string, req *servicesv1.UpdateConversationRequest) (*servicesv1.UpdateConversationResponse, error) {
	ret := _m.Called(ctx, uuid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversation")
	}

	var r0 *servicesv1.UpdateConversationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *servicesv1.UpdateConversationRequest) (*servicesv1.UpdateConversationResponse, error)); ok {
		return rf(ctx, uuid, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *servicesv1.UpdateConversationRequest) *servicesv1.UpdateConversationResponse); ok {
		r0 = rf(ctx, uuid, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesv1.UpdateConversationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *servicesv1.UpdateConversationRequest) error); ok {
		r1 = rf(ctx, uuid, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockConversationService creates a new instance of MockConversationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationService {
	mock := &MockConversationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
