// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	agent "github.com/holmes89/grey-seal/lib/greyseal/agent"

	mock "github.com/stretchr/testify/mock"
)

// MockPullRequestOpener is an autogenerated mock type for the PullRequestOpener type
type MockPullRequestOpener struct {
	mock.Mock
}

// OpenPullRequest provides a mock function with given fields: ctx, req
func (_m *MockPullRequestOpener) OpenPullRequest(ctx context.Context, req agent.OpenPullRequestRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for OpenPullRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, agent.OpenPullRequestRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, agent.OpenPullRequestRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, agent.OpenPullRequestRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPullRequestOpener creates a new instance of MockPullRequestOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestOpener {
	mock := &MockPullRequestOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
