// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	greysealv1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockAgentRunRepository is an autogenerated mock type for the AgentRunRepository type
type MockAgentRunRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, run
func (_m *MockAgentRunRepository) Create(ctx context.Context, run *greysealv1.AgentRun) error {
	ret := _m.Called(ctx, run)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *greysealv1.AgentRun) error); ok {
		r0 = rf(ctx, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAgentRunRepository) Get(ctx context.Context, id string) (*greysealv1.AgentRun, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *greysealv1.AgentRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*greysealv1.AgentRun, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *greysealv1.AgentRun); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*greysealv1.AgentRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, cursor, limit, filter
func (_m *MockAgentRunRepository) List(ctx context.Context, cursor string, limit uint, filter map[string][]interface{}) ([]*greysealv1.AgentRun, error) {
	ret := _m.Called(ctx, cursor, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*greysealv1.AgentRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, map[string][]interface{}) ([]*greysealv1.AgentRun, error)); ok {
		return rf(ctx, cursor, limit, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, map[string][]interface{}) []*greysealv1.AgentRun); ok {
		r0 = rf(ctx, cursor, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*greysealv1.AgentRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, map[string][]interface{}) error); ok {
		r1 = rf(ctx, cursor, limit, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, run
func (_m *MockAgentRunRepository) Update(ctx context.Context, id string, run *greysealv1.AgentRun) error {
	ret := _m.Called(ctx, id, run)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *greysealv1.AgentRun) error); ok {
		r0 = rf(ctx, id, run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAgentRunRepository creates a new instance of MockAgentRunRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRunRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRunRepository {
	mock := &MockAgentRunRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
