// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	agent "github.com/holmes89/grey-seal/lib/greyseal/agent"

	greysealv1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockAgentService is an autogenerated mock type for the AgentService type
type MockAgentService struct {
	mock.Mock
}

// GetAgentRun provides a mock function with given fields: ctx, runUUID
func (_m *MockAgentService) GetAgentRun(ctx context.Context, runUUID string) (*greysealv1.AgentRun, error) {
	ret := _m.Called(ctx, runUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentRun")
	}

	var r0 *greysealv1.AgentRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*greysealv1.AgentRun, error)); ok {
		return rf(ctx, runUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *greysealv1.AgentRun); ok {
		r0 = rf(ctx, runUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*greysealv1.AgentRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, runUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunAgentTask provides a mock function with given fields: ctx, req
func (_m *MockAgentService) RunAgentTask(ctx context.Context, req agent.RunAgentTaskRequest) (*greysealv1.AgentRun, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RunAgentTask")
	}

	var r0 *greysealv1.AgentRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, agent.RunAgentTaskRequest) (*greysealv1.AgentRun, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, agent.RunAgentTaskRequest) *greysealv1.AgentRun); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*greysealv1.AgentRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, agent.RunAgentTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StreamAgentRun provides a mock function with given fields: ctx, runUUID, stream
func (_m *MockAgentService) StreamAgentRun(ctx context.Context, runUUID string, stream func(agent.AgentRunEvent) error) error {
	ret := _m.Called(ctx, runUUID, stream)

	if len(ret) == 0 {
		panic("no return value specified for StreamAgentRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(agent.AgentRunEvent) error) error); ok {
		r0 = rf(ctx, runUUID, stream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAgentService creates a new instance of MockAgentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentService {
	mock := &MockAgentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
