// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	agent "github.com/holmes89/grey-seal/lib/greyseal/agent"

	mock "github.com/stretchr/testify/mock"
)

// MockToolProvider is an autogenerated mock type for the ToolProvider type
type MockToolProvider struct {
	mock.Mock
}

// Session provides a mock function with given fields: ctx
func (_m *MockToolProvider) Session(ctx context.Context) (agent.ToolSession, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Session")
	}

	var r0 agent.ToolSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (agent.ToolSession, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) agent.ToolSession); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(agent.ToolSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockToolProvider creates a new instance of MockToolProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolProvider {
	mock := &MockToolProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
