// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	agent "github.com/holmes89/grey-seal/lib/greyseal/agent"

	mock "github.com/stretchr/testify/mock"
)

// MockToolSession is an autogenerated mock type for the ToolSession type
type MockToolSession struct {
	mock.Mock
}

// CallTool provides a mock function with given fields: ctx, name, args
func (_m *MockToolSession) CallTool(ctx context.Context, name string, args map[string]interface{}) (string, error) {
	ret := _m.Called(ctx, name, args)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (string, error)); ok {
		return rf(ctx, name, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, name, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, name, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with no fields
func (_m *MockToolSession) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListTools provides a mock function with given fields: ctx
func (_m *MockToolSession) ListTools(ctx context.Context) ([]agent.ToolDef, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTools")
	}

	var r0 []agent.ToolDef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]agent.ToolDef, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []agent.ToolDef); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agent.ToolDef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockToolSession creates a new instance of MockToolSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolSession {
	mock := &MockToolSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
