// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	agent "github.com/holmes89/grey-seal/lib/greyseal/agent"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionRunner is an autogenerated mock type for the SessionRunner type
type MockSessionRunner struct {
	mock.Mock
}

// GetSessionStatus provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionRunner) GetSessionStatus(ctx context.Context, sessionID string) (string, string, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionStatus")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, sessionID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StartSession provides a mock function with given fields: ctx, req
func (_m *MockSessionRunner) StartSession(ctx context.Context, req agent.RunAgentTaskRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, agent.RunAgentTaskRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, agent.RunAgentTaskRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, agent.RunAgentTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StreamSession provides a mock function with given fields: ctx, sessionID, stream
func (_m *MockSessionRunner) StreamSession(ctx context.Context, sessionID string, stream func(agent.AgentRunEvent) error) error {
	ret := _m.Called(ctx, sessionID, stream)

	if len(ret) == 0 {
		panic("no return value specified for StreamSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(agent.AgentRunEvent) error) error); ok {
		r0 = rf(ctx, sessionID, stream)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSessionRunner creates a new instance of MockSessionRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRunner {
	mock := &MockSessionRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
