version: "3.7"
name: greyseal
services:
  api:
    image: ghcr.io/holmes89/greyseal:latest
    restart: always
    build:
      context: ./
      ssh:
        - default
    environment:
      DATABASE_URL: "postgres://postgres:password@db/greyseal?sslmode=disable"
      QDRANT_HOST: "qdrant:6334"
      QDRANT_COLLECTION: "greyseal"
      OLLAMA_HOST: "http://ollama:11434"
      OLLAMA_EMBED_MODEL: "all-minilm"
      OLLAMA_CHAT_MODEL: "deepseek-r1"
    ports:
      - 9000:9000
    networks:
      - web
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_started
      ollama:
        condition: service_started

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greyseal
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d greyseal"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - web

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - web

networks:
  web:
