FROM golang:1.25 AS base

FROM base as deps
WORKDIR "/greyseal"

RUN git config --global url.ssh://git@github.com/.insteadOf https://github.com/
RUN mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
ADD *.mod *.sum ./
ENV GOPRIVATE=github.com/holmes89/archaea
RUN --mount=type=ssh go mod download

FROM deps AS build-env
ADD cmd ./cmd
ADD lib ./lib
ADD lib/repo/migrations /migrations
RUN go build -o worker cmd/worker/main.go
CMD ["/greyseal/worker"]