// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	"github.com/holmes89/archaea/base"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockConversationService is a mock type for the ConversationService interface.
type MockConversationService struct {
	mock.Mock
}

func (_m *MockConversationService) List(ctx context.Context, req base.ListRequest) (base.ListResponse[*v1.Conversation], error) {
	ret := _m.Called(ctx, req)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.ListResponse[*v1.Conversation]), ret.Error(1)
}

func (_m *MockConversationService) Get(ctx context.Context, req base.GetRequest[*v1.Conversation]) (base.GetResponse[*v1.Conversation], error) {
	ret := _m.Called(ctx, req)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.GetResponse[*v1.Conversation]), ret.Error(1)
}

func (_m *MockConversationService) Create(ctx context.Context, data *v1.Conversation) (*v1.Conversation, error) {
	ret := _m.Called(ctx, data)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Conversation), ret.Error(1)
}

func (_m *MockConversationService) Update(ctx context.Context, id string, data *v1.Conversation) (*v1.Conversation, error) {
	ret := _m.Called(ctx, id, data)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Conversation), ret.Error(1)
}

func (_m *MockConversationService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func (_m *MockConversationService) Chat(ctx context.Context, conversationUUID string, content string, stream func(token string) error) (*v1.Message, error) {
	ret := _m.Called(ctx, conversationUUID, content, stream)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Message), ret.Error(1)
}

func (_m *MockConversationService) SubmitFeedback(ctx context.Context, messageUUID string, feedback int32) error {
	ret := _m.Called(ctx, messageUUID, feedback)
	return ret.Error(0)
}

func NewMockConversationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationService {
	m := &MockConversationService{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
