// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/holmes89/grey-seal/lib/greyseal/conversation"
)

// MockLLM is a mock type for the LLM interface.
type MockLLM struct {
	mock.Mock
}

func (_m *MockLLM) Chat(ctx context.Context, messages []conversation.LLMMessage, stream func(token string) error) (string, error) {
	ret := _m.Called(ctx, messages, stream)
	return ret.String(0), ret.Error(1)
}

func NewMockLLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLM {
	m := &MockLLM{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
