// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockMessageRepository is a mock type for the MessageRepository interface.
type MockMessageRepository struct {
	mock.Mock
}

func (_m *MockMessageRepository) Create(ctx context.Context, entity *v1.Message) error {
	ret := _m.Called(ctx, entity)
	return ret.Error(0)
}

func (_m *MockMessageRepository) Update(ctx context.Context, id string, entity *v1.Message) error {
	ret := _m.Called(ctx, id, entity)
	return ret.Error(0)
}

func (_m *MockMessageRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func (_m *MockMessageRepository) Get(ctx context.Context, id string) (*v1.Message, error) {
	ret := _m.Called(ctx, id)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Message), ret.Error(1)
}

func (_m *MockMessageRepository) List(ctx context.Context, cursor string, limit uint, filter map[string][]any) ([]*v1.Message, error) {
	ret := _m.Called(ctx, cursor, limit, filter)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]*v1.Message), ret.Error(1)
}

func (_m *MockMessageRepository) ListByConversation(ctx context.Context, conversationUUID string) ([]*v1.Message, error) {
	ret := _m.Called(ctx, conversationUUID)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]*v1.Message), ret.Error(1)
}

func (_m *MockMessageRepository) UpdateFeedback(ctx context.Context, messageUUID string, feedback int32) error {
	ret := _m.Called(ctx, messageUUID, feedback)
	return ret.Error(0)
}

func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	m := &MockMessageRepository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
