// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/holmes89/grey-seal/lib/greyseal/conversation"
)

// MockSearcher is a mock type for the Searcher interface.
type MockSearcher struct {
	mock.Mock
}

func (_m *MockSearcher) Search(ctx context.Context, query string, limit int32, resourceUUIDs []string) ([]conversation.SearchResult, error) {
	ret := _m.Called(ctx, query, limit, resourceUUIDs)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]conversation.SearchResult), ret.Error(1)
}

func NewMockSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcher {
	m := &MockSearcher{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
