// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockConversationRepository is a mock type for the ConversationRepository interface.
type MockConversationRepository struct {
	mock.Mock
}

func (_m *MockConversationRepository) Create(ctx context.Context, entity *v1.Conversation) error {
	ret := _m.Called(ctx, entity)
	return ret.Error(0)
}

func (_m *MockConversationRepository) Update(ctx context.Context, id string, entity *v1.Conversation) error {
	ret := _m.Called(ctx, id, entity)
	return ret.Error(0)
}

func (_m *MockConversationRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func (_m *MockConversationRepository) Get(ctx context.Context, id string) (*v1.Conversation, error) {
	ret := _m.Called(ctx, id)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Conversation), ret.Error(1)
}

func (_m *MockConversationRepository) List(ctx context.Context, cursor string, limit uint, filter map[string][]any) ([]*v1.Conversation, error) {
	ret := _m.Called(ctx, cursor, limit, filter)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]*v1.Conversation), ret.Error(1)
}

func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	m := &MockConversationRepository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
