// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /Users/joel/dev/grey-seal && make generate

package mocks

import (
	"context"

	"github.com/holmes89/grey-seal/lib/greyseal/conversation"
	mock "github.com/stretchr/testify/mock"
)

// MockResourceCache is a mock type for the ResourceCache interface.
type MockResourceCache struct {
	mock.Mock
}

func (_m *MockResourceCache) Merge(ctx context.Context, conversationUUID string, resources []conversation.CachedResource) error {
	ret := _m.Called(ctx, conversationUUID, resources)
	return ret.Error(0)
}

func (_m *MockResourceCache) List(ctx context.Context, conversationUUID string) ([]conversation.CachedResource, error) {
	ret := _m.Called(ctx, conversationUUID)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]conversation.CachedResource), ret.Error(1)
}

func NewMockResourceCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceCache {
	m := &MockResourceCache{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
