// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/agent.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "schemas.greyseal.services.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceRunAgentTaskProcedure is the fully-qualified name of the AgentService's RunAgentTask
	// RPC.
	AgentServiceRunAgentTaskProcedure = "/schemas.greyseal.services.v1.AgentService/RunAgentTask"
	// AgentServiceGetAgentRunProcedure is the fully-qualified name of the AgentService's GetAgentRun
	// RPC.
	AgentServiceGetAgentRunProcedure = "/schemas.greyseal.services.v1.AgentService/GetAgentRun"
	// AgentServiceStreamAgentRunProcedure is the fully-qualified name of the AgentService's
	// StreamAgentRun RPC.
	AgentServiceStreamAgentRunProcedure = "/schemas.greyseal.services.v1.AgentService/StreamAgentRun"
)

// AgentServiceClient is a client for the schemas.greyseal.services.v1.AgentService service.
type AgentServiceClient interface {
	// RunAgentTask starts a new agentic coding-task run and returns
	// immediately with its initial state; the run continues asynchronously on
	// the provider's side.
	RunAgentTask(context.Context, *connect.Request[services.RunAgentTaskRequest]) (*connect.Response[services.RunAgentTaskResponse], error)
	// GetAgentRun returns the current state of a previously started run.
	GetAgentRun(context.Context, *connect.Request[services.GetAgentRunRequest]) (*connect.Response[services.GetAgentRunResponse], error)
	// StreamAgentRun streams events for a run as they occur, until the run
	// reaches a terminal status.
	StreamAgentRun(context.Context, *connect.Request[services.StreamAgentRunRequest]) (*connect.ServerStreamForClient[services.AgentRunEvent], error)
}

// NewAgentServiceClient constructs a client for the schemas.greyseal.services.v1.AgentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := services.File_schemas_greyseal_v1_services_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		runAgentTask: connect.NewClient[services.RunAgentTaskRequest, services.RunAgentTaskResponse](
			httpClient,
			baseURL+AgentServiceRunAgentTaskProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RunAgentTask")),
			connect.WithClientOptions(opts...),
		),
		getAgentRun: connect.NewClient[services.GetAgentRunRequest, services.GetAgentRunResponse](
			httpClient,
			baseURL+AgentServiceGetAgentRunProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetAgentRun")),
			connect.WithClientOptions(opts...),
		),
		streamAgentRun: connect.NewClient[services.StreamAgentRunRequest, services.AgentRunEvent](
			httpClient,
			baseURL+AgentServiceStreamAgentRunProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamAgentRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	runAgentTask   *connect.Client[services.RunAgentTaskRequest, services.RunAgentTaskResponse]
	getAgentRun    *connect.Client[services.GetAgentRunRequest, services.GetAgentRunResponse]
	streamAgentRun *connect.Client[services.StreamAgentRunRequest, services.AgentRunEvent]
}

// RunAgentTask calls schemas.greyseal.services.v1.AgentService.RunAgentTask.
func (c *agentServiceClient) RunAgentTask(ctx context.Context, req *connect.Request[services.RunAgentTaskRequest]) (*connect.Response[services.RunAgentTaskResponse], error) {
	return c.runAgentTask.CallUnary(ctx, req)
}

// GetAgentRun calls schemas.greyseal.services.v1.AgentService.GetAgentRun.
func (c *agentServiceClient) GetAgentRun(ctx context.Context, req *connect.Request[services.GetAgentRunRequest]) (*connect.Response[services.GetAgentRunResponse], error) {
	return c.getAgentRun.CallUnary(ctx, req)
}

// StreamAgentRun calls schemas.greyseal.services.v1.AgentService.StreamAgentRun.
func (c *agentServiceClient) StreamAgentRun(ctx context.Context, req *connect.Request[services.StreamAgentRunRequest]) (*connect.ServerStreamForClient[services.AgentRunEvent], error) {
	return c.streamAgentRun.CallServerStream(ctx, req)
}

// AgentServiceHandler is an implementation of the schemas.greyseal.services.v1.AgentService
// service.
type AgentServiceHandler interface {
	// RunAgentTask starts a new agentic coding-task run and returns
	// immediately with its initial state; the run continues asynchronously on
	// the provider's side.
	RunAgentTask(context.Context, *connect.Request[services.RunAgentTaskRequest]) (*connect.Response[services.RunAgentTaskResponse], error)
	// GetAgentRun returns the current state of a previously started run.
	GetAgentRun(context.Context, *connect.Request[services.GetAgentRunRequest]) (*connect.Response[services.GetAgentRunResponse], error)
	// StreamAgentRun streams events for a run as they occur, until the run
	// reaches a terminal status.
	StreamAgentRun(context.Context, *connect.Request[services.StreamAgentRunRequest], *connect.ServerStream[services.AgentRunEvent]) error
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := services.File_schemas_greyseal_v1_services_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceRunAgentTaskHandler := connect.NewUnaryHandler(
		AgentServiceRunAgentTaskProcedure,
		svc.RunAgentTask,
		connect.WithSchema(agentServiceMethods.ByName("RunAgentTask")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAgentRunHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentRunProcedure,
		svc.GetAgentRun,
		connect.WithSchema(agentServiceMethods.ByName("GetAgentRun")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStreamAgentRunHandler := connect.NewServerStreamHandler(
		AgentServiceStreamAgentRunProcedure,
		svc.StreamAgentRun,
		connect.WithSchema(agentServiceMethods.ByName("StreamAgentRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.services.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceRunAgentTaskProcedure:
			agentServiceRunAgentTaskHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentRunProcedure:
			agentServiceGetAgentRunHandler.ServeHTTP(w, r)
		case AgentServiceStreamAgentRunProcedure:
			agentServiceStreamAgentRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) RunAgentTask(context.Context, *connect.Request[services.RunAgentTaskRequest]) (*connect.Response[services.RunAgentTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.AgentService.RunAgentTask is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgentRun(context.Context, *connect.Request[services.GetAgentRunRequest]) (*connect.Response[services.GetAgentRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.AgentService.GetAgentRun is not implemented"))
}

func (UnimplementedAgentServiceHandler) StreamAgentRun(context.Context, *connect.Request[services.StreamAgentRunRequest], *connect.ServerStream[services.AgentRunEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.AgentService.StreamAgentRun is not implemented"))
}
