// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/conversation.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConversationServiceName is the fully-qualified name of the ConversationService service.
	ConversationServiceName = "schemas.greyseal.services.v1.ConversationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConversationServiceCreateConversationProcedure is the fully-qualified name of the
	// ConversationService's CreateConversation RPC.
	ConversationServiceCreateConversationProcedure = "/schemas.greyseal.services.v1.ConversationService/CreateConversation"
	// ConversationServiceGetConversationProcedure is the fully-qualified name of the
	// ConversationService's GetConversation RPC.
	ConversationServiceGetConversationProcedure = "/schemas.greyseal.services.v1.ConversationService/GetConversation"
	// ConversationServiceListConversationsProcedure is the fully-qualified name of the
	// ConversationService's ListConversations RPC.
	ConversationServiceListConversationsProcedure = "/schemas.greyseal.services.v1.ConversationService/ListConversations"
	// ConversationServiceUpdateConversationProcedure is the fully-qualified name of the
	// ConversationService's UpdateConversation RPC.
	ConversationServiceUpdateConversationProcedure = "/schemas.greyseal.services.v1.ConversationService/UpdateConversation"
	// ConversationServiceDeleteConversationProcedure is the fully-qualified name of the
	// ConversationService's DeleteConversation RPC.
	ConversationServiceDeleteConversationProcedure = "/schemas.greyseal.services.v1.ConversationService/DeleteConversation"
	// ConversationServiceChatProcedure is the fully-qualified name of the ConversationService's Chat
	// RPC.
	ConversationServiceChatProcedure = "/schemas.greyseal.services.v1.ConversationService/Chat"
	// ConversationServiceSubmitFeedbackProcedure is the fully-qualified name of the
	// ConversationService's SubmitFeedback RPC.
	ConversationServiceSubmitFeedbackProcedure = "/schemas.greyseal.services.v1.ConversationService/SubmitFeedback"
)

// ConversationServiceClient is a client for the schemas.greyseal.services.v1.ConversationService
// service.
type ConversationServiceClient interface {
	CreateConversation(context.Context, *connect.Request[services.CreateConversationRequest]) (*connect.Response[services.CreateConversationResponse], error)
	GetConversation(context.Context, *connect.Request[services.GetConversationRequest]) (*connect.Response[services.GetConversationResponse], error)
	ListConversations(context.Context, *connect.Request[services.ListConversationsRequest]) (*connect.Response[services.ListConversationsResponse], error)
	UpdateConversation(context.Context, *connect.Request[services.UpdateConversationRequest]) (*connect.Response[services.UpdateConversationResponse], error)
	DeleteConversation(context.Context, *connect.Request[services.DeleteConversationRequest]) (*connect.Response[services.DeleteConversationResponse], error)
	// Chat sends a user message and streams back the assistant response token by token.
	Chat(context.Context, *connect.Request[services.ChatRequest]) (*connect.ServerStreamForClient[services.ChatResponse], error)
	// SubmitFeedback records user feedback on an assistant message.
	SubmitFeedback(context.Context, *connect.Request[services.SubmitFeedbackRequest]) (*connect.Response[services.SubmitFeedbackResponse], error)
}

// NewConversationServiceClient constructs a client for the
// schemas.greyseal.services.v1.ConversationService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConversationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConversationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	conversationServiceMethods := services.File_schemas_greyseal_v1_services_conversation_proto.Services().ByName("ConversationService").Methods()
	return &conversationServiceClient{
		createConversation: connect.NewClient[services.CreateConversationRequest, services.CreateConversationResponse](
			httpClient,
			baseURL+ConversationServiceCreateConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("CreateConversation")),
			connect.WithClientOptions(opts...),
		),
		getConversation: connect.NewClient[services.GetConversationRequest, services.GetConversationResponse](
			httpClient,
			baseURL+ConversationServiceGetConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("GetConversation")),
			connect.WithClientOptions(opts...),
		),
		listConversations: connect.NewClient[services.ListConversationsRequest, services.ListConversationsResponse](
			httpClient,
			baseURL+ConversationServiceListConversationsProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("ListConversations")),
			connect.WithClientOptions(opts...),
		),
		updateConversation: connect.NewClient[services.UpdateConversationRequest, services.UpdateConversationResponse](
			httpClient,
			baseURL+ConversationServiceUpdateConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("UpdateConversation")),
			connect.WithClientOptions(opts...),
		),
		deleteConversation: connect.NewClient[services.DeleteConversationRequest, services.DeleteConversationResponse](
			httpClient,
			baseURL+ConversationServiceDeleteConversationProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("DeleteConversation")),
			connect.WithClientOptions(opts...),
		),
		chat: connect.NewClient[services.ChatRequest, services.ChatResponse](
			httpClient,
			baseURL+ConversationServiceChatProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("Chat")),
			connect.WithClientOptions(opts...),
		),
		submitFeedback: connect.NewClient[services.SubmitFeedbackRequest, services.SubmitFeedbackResponse](
			httpClient,
			baseURL+ConversationServiceSubmitFeedbackProcedure,
			connect.WithSchema(conversationServiceMethods.ByName("SubmitFeedback")),
			connect.WithClientOptions(opts...),
		),
	}
}

// conversationServiceClient implements ConversationServiceClient.
type conversationServiceClient struct {
	createConversation *connect.Client[services.CreateConversationRequest, services.CreateConversationResponse]
	getConversation    *connect.Client[services.GetConversationRequest, services.GetConversationResponse]
	listConversations  *connect.Client[services.ListConversationsRequest, services.ListConversationsResponse]
	updateConversation *connect.Client[services.UpdateConversationRequest, services.UpdateConversationResponse]
	deleteConversation *connect.Client[services.DeleteConversationRequest, services.DeleteConversationResponse]
	chat               *connect.Client[services.ChatRequest, services.ChatResponse]
	submitFeedback     *connect.Client[services.SubmitFeedbackRequest, services.SubmitFeedbackResponse]
}

// CreateConversation calls schemas.greyseal.services.v1.ConversationService.CreateConversation.
func (c *conversationServiceClient) CreateConversation(ctx context.Context, req *connect.Request[services.CreateConversationRequest]) (*connect.Response[services.CreateConversationResponse], error) {
	return c.createConversation.CallUnary(ctx, req)
}

// GetConversation calls schemas.greyseal.services.v1.ConversationService.GetConversation.
func (c *conversationServiceClient) GetConversation(ctx context.Context, req *connect.Request[services.GetConversationRequest]) (*connect.Response[services.GetConversationResponse], error) {
	return c.getConversation.CallUnary(ctx, req)
}

// ListConversations calls schemas.greyseal.services.v1.ConversationService.ListConversations.
func (c *conversationServiceClient) ListConversations(ctx context.Context, req *connect.Request[services.ListConversationsRequest]) (*connect.Response[services.ListConversationsResponse], error) {
	return c.listConversations.CallUnary(ctx, req)
}

// UpdateConversation calls schemas.greyseal.services.v1.ConversationService.UpdateConversation.
func (c *conversationServiceClient) UpdateConversation(ctx context.Context, req *connect.Request[services.UpdateConversationRequest]) (*connect.Response[services.UpdateConversationResponse], error) {
	return c.updateConversation.CallUnary(ctx, req)
}

// DeleteConversation calls schemas.greyseal.services.v1.ConversationService.DeleteConversation.
func (c *conversationServiceClient) DeleteConversation(ctx context.Context, req *connect.Request[services.DeleteConversationRequest]) (*connect.Response[services.DeleteConversationResponse], error) {
	return c.deleteConversation.CallUnary(ctx, req)
}

// Chat calls schemas.greyseal.services.v1.ConversationService.Chat.
func (c *conversationServiceClient) Chat(ctx context.Context, req *connect.Request[services.ChatRequest]) (*connect.ServerStreamForClient[services.ChatResponse], error) {
	return c.chat.CallServerStream(ctx, req)
}

// SubmitFeedback calls schemas.greyseal.services.v1.ConversationService.SubmitFeedback.
func (c *conversationServiceClient) SubmitFeedback(ctx context.Context, req *connect.Request[services.SubmitFeedbackRequest]) (*connect.Response[services.SubmitFeedbackResponse], error) {
	return c.submitFeedback.CallUnary(ctx, req)
}

// ConversationServiceHandler is an implementation of the
// schemas.greyseal.services.v1.ConversationService service.
type ConversationServiceHandler interface {
	CreateConversation(context.Context, *connect.Request[services.CreateConversationRequest]) (*connect.Response[services.CreateConversationResponse], error)
	GetConversation(context.Context, *connect.Request[services.GetConversationRequest]) (*connect.Response[services.GetConversationResponse], error)
	ListConversations(context.Context, *connect.Request[services.ListConversationsRequest]) (*connect.Response[services.ListConversationsResponse], error)
	UpdateConversation(context.Context, *connect.Request[services.UpdateConversationRequest]) (*connect.Response[services.UpdateConversationResponse], error)
	DeleteConversation(context.Context, *connect.Request[services.DeleteConversationRequest]) (*connect.Response[services.DeleteConversationResponse], error)
	// Chat sends a user message and streams back the assistant response token by token.
	Chat(context.Context, *connect.Request[services.ChatRequest], *connect.ServerStream[services.ChatResponse]) error
	// SubmitFeedback records user feedback on an assistant message.
	SubmitFeedback(context.Context, *connect.Request[services.SubmitFeedbackRequest]) (*connect.Response[services.SubmitFeedbackResponse], error)
}

// NewConversationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConversationServiceHandler(svc ConversationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	conversationServiceMethods := services.File_schemas_greyseal_v1_services_conversation_proto.Services().ByName("ConversationService").Methods()
	conversationServiceCreateConversationHandler := connect.NewUnaryHandler(
		ConversationServiceCreateConversationProcedure,
		svc.CreateConversation,
		connect.WithSchema(conversationServiceMethods.ByName("CreateConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceGetConversationHandler := connect.NewUnaryHandler(
		ConversationServiceGetConversationProcedure,
		svc.GetConversation,
		connect.WithSchema(conversationServiceMethods.ByName("GetConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceListConversationsHandler := connect.NewUnaryHandler(
		ConversationServiceListConversationsProcedure,
		svc.ListConversations,
		connect.WithSchema(conversationServiceMethods.ByName("ListConversations")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceUpdateConversationHandler := connect.NewUnaryHandler(
		ConversationServiceUpdateConversationProcedure,
		svc.UpdateConversation,
		connect.WithSchema(conversationServiceMethods.ByName("UpdateConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceDeleteConversationHandler := connect.NewUnaryHandler(
		ConversationServiceDeleteConversationProcedure,
		svc.DeleteConversation,
		connect.WithSchema(conversationServiceMethods.ByName("DeleteConversation")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceChatHandler := connect.NewServerStreamHandler(
		ConversationServiceChatProcedure,
		svc.Chat,
		connect.WithSchema(conversationServiceMethods.ByName("Chat")),
		connect.WithHandlerOptions(opts...),
	)
	conversationServiceSubmitFeedbackHandler := connect.NewUnaryHandler(
		ConversationServiceSubmitFeedbackProcedure,
		svc.SubmitFeedback,
		connect.WithSchema(conversationServiceMethods.ByName("SubmitFeedback")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.services.v1.ConversationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConversationServiceCreateConversationProcedure:
			conversationServiceCreateConversationHandler.ServeHTTP(w, r)
		case ConversationServiceGetConversationProcedure:
			conversationServiceGetConversationHandler.ServeHTTP(w, r)
		case ConversationServiceListConversationsProcedure:
			conversationServiceListConversationsHandler.ServeHTTP(w, r)
		case ConversationServiceUpdateConversationProcedure:
			conversationServiceUpdateConversationHandler.ServeHTTP(w, r)
		case ConversationServiceDeleteConversationProcedure:
			conversationServiceDeleteConversationHandler.ServeHTTP(w, r)
		case ConversationServiceChatProcedure:
			conversationServiceChatHandler.ServeHTTP(w, r)
		case ConversationServiceSubmitFeedbackProcedure:
			conversationServiceSubmitFeedbackHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConversationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConversationServiceHandler struct{}

func (UnimplementedConversationServiceHandler) CreateConversation(context.Context, *connect.Request[services.CreateConversationRequest]) (*connect.Response[services.CreateConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.CreateConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) GetConversation(context.Context, *connect.Request[services.GetConversationRequest]) (*connect.Response[services.GetConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.GetConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) ListConversations(context.Context, *connect.Request[services.ListConversationsRequest]) (*connect.Response[services.ListConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.ListConversations is not implemented"))
}

func (UnimplementedConversationServiceHandler) UpdateConversation(context.Context, *connect.Request[services.UpdateConversationRequest]) (*connect.Response[services.UpdateConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.UpdateConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) DeleteConversation(context.Context, *connect.Request[services.DeleteConversationRequest]) (*connect.Response[services.DeleteConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.DeleteConversation is not implemented"))
}

func (UnimplementedConversationServiceHandler) Chat(context.Context, *connect.Request[services.ChatRequest], *connect.ServerStream[services.ChatResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.Chat is not implemented"))
}

func (UnimplementedConversationServiceHandler) SubmitFeedback(context.Context, *connect.Request[services.SubmitFeedbackRequest]) (*connect.Response[services.SubmitFeedbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ConversationService.SubmitFeedback is not implemented"))
}
