// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/role.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RoleServiceName is the fully-qualified name of the RoleService service.
	RoleServiceName = "schemas.greyseal.services.v1.RoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RoleServiceCreateRoleProcedure is the fully-qualified name of the RoleService's CreateRole RPC.
	RoleServiceCreateRoleProcedure = "/schemas.greyseal.services.v1.RoleService/CreateRole"
	// RoleServiceGetRoleProcedure is the fully-qualified name of the RoleService's GetRole RPC.
	RoleServiceGetRoleProcedure = "/schemas.greyseal.services.v1.RoleService/GetRole"
	// RoleServiceListRolesProcedure is the fully-qualified name of the RoleService's ListRoles RPC.
	RoleServiceListRolesProcedure = "/schemas.greyseal.services.v1.RoleService/ListRoles"
	// RoleServiceUpdateRoleProcedure is the fully-qualified name of the RoleService's UpdateRole RPC.
	RoleServiceUpdateRoleProcedure = "/schemas.greyseal.services.v1.RoleService/UpdateRole"
	// RoleServiceDeleteRoleProcedure is the fully-qualified name of the RoleService's DeleteRole RPC.
	RoleServiceDeleteRoleProcedure = "/schemas.greyseal.services.v1.RoleService/DeleteRole"
)

// RoleServiceClient is a client for the schemas.greyseal.services.v1.RoleService service.
type RoleServiceClient interface {
	CreateRole(context.Context, *connect.Request[services.CreateRoleRequest]) (*connect.Response[services.CreateRoleResponse], error)
	GetRole(context.Context, *connect.Request[services.GetRoleRequest]) (*connect.Response[services.GetRoleResponse], error)
	ListRoles(context.Context, *connect.Request[services.ListRolesRequest]) (*connect.Response[services.ListRolesResponse], error)
	UpdateRole(context.Context, *connect.Request[services.UpdateRoleRequest]) (*connect.Response[services.UpdateRoleResponse], error)
	DeleteRole(context.Context, *connect.Request[services.DeleteRoleRequest]) (*connect.Response[services.DeleteRoleResponse], error)
}

// NewRoleServiceClient constructs a client for the schemas.greyseal.services.v1.RoleService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	roleServiceMethods := services.File_schemas_greyseal_v1_services_role_proto.Services().ByName("RoleService").Methods()
	return &roleServiceClient{
		createRole: connect.NewClient[services.CreateRoleRequest, services.CreateRoleResponse](
			httpClient,
			baseURL+RoleServiceCreateRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		getRole: connect.NewClient[services.GetRoleRequest, services.GetRoleResponse](
			httpClient,
			baseURL+RoleServiceGetRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("GetRole")),
			connect.WithClientOptions(opts...),
		),
		listRoles: connect.NewClient[services.ListRolesRequest, services.ListRolesResponse](
			httpClient,
			baseURL+RoleServiceListRolesProcedure,
			connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[services.UpdateRoleRequest, services.UpdateRoleResponse](
			httpClient,
			baseURL+RoleServiceUpdateRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		deleteRole: connect.NewClient[services.DeleteRoleRequest, services.DeleteRoleResponse](
			httpClient,
			baseURL+RoleServiceDeleteRoleProcedure,
			connect.WithSchema(roleServiceMethods.ByName("DeleteRole")),
			connect.WithClientOptions(opts...),
		),
	}
}

// roleServiceClient implements RoleServiceClient.
type roleServiceClient struct {
	createRole *connect.Client[services.CreateRoleRequest, services.CreateRoleResponse]
	getRole    *connect.Client[services.GetRoleRequest, services.GetRoleResponse]
	listRoles  *connect.Client[services.ListRolesRequest, services.ListRolesResponse]
	updateRole *connect.Client[services.UpdateRoleRequest, services.UpdateRoleResponse]
	deleteRole *connect.Client[services.DeleteRoleRequest, services.DeleteRoleResponse]
}

// CreateRole calls schemas.greyseal.services.v1.RoleService.CreateRole.
func (c *roleServiceClient) CreateRole(ctx context.Context, req *connect.Request[services.CreateRoleRequest]) (*connect.Response[services.CreateRoleResponse], error) {
	return c.createRole.CallUnary(ctx, req)
}

// GetRole calls schemas.greyseal.services.v1.RoleService.GetRole.
func (c *roleServiceClient) GetRole(ctx context.Context, req *connect.Request[services.GetRoleRequest]) (*connect.Response[services.GetRoleResponse], error) {
	return c.getRole.CallUnary(ctx, req)
}

// ListRoles calls schemas.greyseal.services.v1.RoleService.ListRoles.
func (c *roleServiceClient) ListRoles(ctx context.Context, req *connect.Request[services.ListRolesRequest]) (*connect.Response[services.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// UpdateRole calls schemas.greyseal.services.v1.RoleService.UpdateRole.
func (c *roleServiceClient) UpdateRole(ctx context.Context, req *connect.Request[services.UpdateRoleRequest]) (*connect.Response[services.UpdateRoleResponse], error) {
	return c.updateRole.CallUnary(ctx, req)
}

// DeleteRole calls schemas.greyseal.services.v1.RoleService.DeleteRole.
func (c *roleServiceClient) DeleteRole(ctx context.Context, req *connect.Request[services.DeleteRoleRequest]) (*connect.Response[services.DeleteRoleResponse], error) {
	return c.deleteRole.CallUnary(ctx, req)
}

// RoleServiceHandler is an implementation of the schemas.greyseal.services.v1.RoleService service.
type RoleServiceHandler interface {
	CreateRole(context.Context, *connect.Request[services.CreateRoleRequest]) (*connect.Response[services.CreateRoleResponse], error)
	GetRole(context.Context, *connect.Request[services.GetRoleRequest]) (*connect.Response[services.GetRoleResponse], error)
	ListRoles(context.Context, *connect.Request[services.ListRolesRequest]) (*connect.Response[services.ListRolesResponse], error)
	UpdateRole(context.Context, *connect.Request[services.UpdateRoleRequest]) (*connect.Response[services.UpdateRoleResponse], error)
	DeleteRole(context.Context, *connect.Request[services.DeleteRoleRequest]) (*connect.Response[services.DeleteRoleResponse], error)
}

// NewRoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRoleServiceHandler(svc RoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	roleServiceMethods := services.File_schemas_greyseal_v1_services_role_proto.Services().ByName("RoleService").Methods()
	roleServiceCreateRoleHandler := connect.NewUnaryHandler(
		RoleServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(roleServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceGetRoleHandler := connect.NewUnaryHandler(
		RoleServiceGetRoleProcedure,
		svc.GetRole,
		connect.WithSchema(roleServiceMethods.ByName("GetRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceListRolesHandler := connect.NewUnaryHandler(
		RoleServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(roleServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceUpdateRoleHandler := connect.NewUnaryHandler(
		RoleServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(roleServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	roleServiceDeleteRoleHandler := connect.NewUnaryHandler(
		RoleServiceDeleteRoleProcedure,
		svc.DeleteRole,
		connect.WithSchema(roleServiceMethods.ByName("DeleteRole")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.services.v1.RoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RoleServiceCreateRoleProcedure:
			roleServiceCreateRoleHandler.ServeHTTP(w, r)
		case RoleServiceGetRoleProcedure:
			roleServiceGetRoleHandler.ServeHTTP(w, r)
		case RoleServiceListRolesProcedure:
			roleServiceListRolesHandler.ServeHTTP(w, r)
		case RoleServiceUpdateRoleProcedure:
			roleServiceUpdateRoleHandler.ServeHTTP(w, r)
		case RoleServiceDeleteRoleProcedure:
			roleServiceDeleteRoleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRoleServiceHandler struct{}

func (UnimplementedRoleServiceHandler) CreateRole(context.Context, *connect.Request[services.CreateRoleRequest]) (*connect.Response[services.CreateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.RoleService.CreateRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) GetRole(context.Context, *connect.Request[services.GetRoleRequest]) (*connect.Response[services.GetRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.RoleService.GetRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) ListRoles(context.Context, *connect.Request[services.ListRolesRequest]) (*connect.Response[services.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.RoleService.ListRoles is not implemented"))
}

func (UnimplementedRoleServiceHandler) UpdateRole(context.Context, *connect.Request[services.UpdateRoleRequest]) (*connect.Response[services.UpdateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.RoleService.UpdateRole is not implemented"))
}

func (UnimplementedRoleServiceHandler) DeleteRole(context.Context, *connect.Request[services.DeleteRoleRequest]) (*connect.Response[services.DeleteRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.RoleService.DeleteRole is not implemented"))
}
