// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: schemas/greyseal/v1/services/agent.proto

package servicesv1

import (
	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunAgentTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider: "claude" (only implemented value); "ollama:<model>" reserved.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RepoUrl  string `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// github_token authorizes cloning (and, for Claude, opening a PR against)
	// repo_url. Never persisted — used only to start the provider session.
	GithubToken string `protobuf:"bytes,3,opt,name=github_token,json=githubToken,proto3" json:"github_token,omitempty"`
	// branch to check out; defaults to the repository's default branch.
	Branch string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	// task_description is what the agent should do.
	TaskDescription string `protobuf:"bytes,5,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	// rubric is the grading criteria for the provider's outcome-graded loop,
	// e.g. "go build ./... succeeds, go test ./... passes, no
	// TODO(agent) markers remain".
	Rubric        string `protobuf:"bytes,6,opt,name=rubric,proto3" json:"rubric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentTaskRequest) Reset() {
	*x = RunAgentTaskRequest{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentTaskRequest) ProtoMessage() {}

func (x *RunAgentTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentTaskRequest.ProtoReflect.Descriptor instead.
func (*RunAgentTaskRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RunAgentTaskRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RunAgentTaskRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *RunAgentTaskRequest) GetGithubToken() string {
	if x != nil {
		return x.GithubToken
	}
	return ""
}

func (x *RunAgentTaskRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *RunAgentTaskRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *RunAgentTaskRequest) GetRubric() string {
	if x != nil {
		return x.Rubric
	}
	return ""
}

type RunAgentTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.AgentRun           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentTaskResponse) Reset() {
	*x = RunAgentTaskResponse{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentTaskResponse) ProtoMessage() {}

func (x *RunAgentTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentTaskResponse.ProtoReflect.Descriptor instead.
func (*RunAgentTaskResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RunAgentTaskResponse) GetData() *v1.AgentRun {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAgentRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRunRequest) Reset() {
	*x = GetAgentRunRequest{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRunRequest) ProtoMessage() {}

func (x *GetAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRunRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentRunRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetAgentRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.AgentRun           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRunResponse) Reset() {
	*x = GetAgentRunResponse{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRunResponse) ProtoMessage() {}

func (x *GetAgentRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRunResponse.ProtoReflect.Descriptor instead.
func (*GetAgentRunResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentRunResponse) GetData() *v1.AgentRun {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListAgentRunsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status filters to exactly this value (e.g. "running", "idle",
	// "terminated") when set; unset/empty returns every run.
	Status *string `protobuf:"bytes,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// count caps the number of runs returned (newest-first); 0/unset means
	// no cap.
	Count         *int32 `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentRunsRequest) Reset() {
	*x = ListAgentRunsRequest{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentRunsRequest) ProtoMessage() {}

func (x *ListAgentRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentRunsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentRunsRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentRunsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ListAgentRunsRequest) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type ListAgentRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v1.AgentRun         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentRunsResponse) Reset() {
	*x = ListAgentRunsResponse{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentRunsResponse) ProtoMessage() {}

func (x *ListAgentRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentRunsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentRunsResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentRunsResponse) GetData() []*v1.AgentRun {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListAgentRunsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamAgentRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAgentRunRequest) Reset() {
	*x = StreamAgentRunRequest{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAgentRunRequest) ProtoMessage() {}

func (x *StreamAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAgentRunRequest.ProtoReflect.Descriptor instead.
func (*StreamAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StreamAgentRunRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// AgentRunEvent is one relayed event from a running agent session.
type AgentRunEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: the provider event type, e.g. "agent.message", "agent.tool_use",
	// "session.status_idle", "session.status_terminated".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// message is human-readable text for message/tool-use events.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// status is populated on status-change events: "running" | "idle" |
	// "terminated" | "error".
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRunEvent) Reset() {
	*x = AgentRunEvent{}
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunEvent) ProtoMessage() {}

func (x *AgentRunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunEvent.ProtoReflect.Descriptor instead.
func (*AgentRunEvent) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentRunEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentRunEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentRunEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_schemas_greyseal_v1_services_agent_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_services_agent_proto_rawDesc = "" +
	"\n" +
	"(schemas/greyseal/v1/services/agent.proto\x12\x1cschemas.greyseal.services.v1\x1a\x1fschemas/greyseal/v1/agent.proto\"\xca\x01\n" +
	"\x13RunAgentTaskRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12!\n" +
	"\fgithub_token\x18\x03 \x01(\tR\vgithubToken\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12)\n" +
	"\x10task_description\x18\x05 \x01(\tR\x0ftaskDescription\x12\x16\n" +
	"\x06rubric\x18\x06 \x01(\tR\x06rubric\"I\n" +
	"\x14RunAgentTaskResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.AgentRunR\x04data\"(\n" +
	"\x12GetAgentRunRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"H\n" +
	"\x13GetAgentRunResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.AgentRunR\x04data\"c\n" +
	"\x14ListAgentRunsRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\x02 \x01(\x05H\x01R\x05count\x88\x01\x01B\t\n" +
	"\a_statusB\b\n" +
	"\x06_count\"`\n" +
	"\x15ListAgentRunsResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.schemas.greyseal.v1.AgentRunR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"+\n" +
	"\x15StreamAgentRunRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"U\n" +
	"\rAgentRunEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xf1\x03\n" +
	"\fAgentService\x12w\n" +
	"\fRunAgentTask\x121.schemas.greyseal.services.v1.RunAgentTaskRequest\x1a2.schemas.greyseal.services.v1.RunAgentTaskResponse\"\x00\x12t\n" +
	"\vGetAgentRun\x120.schemas.greyseal.services.v1.GetAgentRunRequest\x1a1.schemas.greyseal.services.v1.GetAgentRunResponse\"\x00\x12z\n" +
	"\rListAgentRuns\x122.schemas.greyseal.services.v1.ListAgentRunsRequest\x1a3.schemas.greyseal.services.v1.ListAgentRunsResponse\"\x00\x12v\n" +
	"\x0eStreamAgentRun\x123.schemas.greyseal.services.v1.StreamAgentRunRequest\x1a+.schemas.greyseal.services.v1.AgentRunEvent\"\x000\x01B\x8c\x02\n" +
	" com.schemas.greyseal.services.v1B\n" +
	"AgentProtoP\x01ZIgithub.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services;servicesv1\xa2\x02\x03SGS\xaa\x02\x1cSchemas.Greyseal.Services.V1\xca\x02\x1cSchemas\\Greyseal\\Services\\V1\xe2\x02(Schemas\\Greyseal\\Services\\V1\\GPBMetadata\xea\x02\x1fSchemas::Greyseal::Services::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_services_agent_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_services_agent_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_services_agent_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_services_agent_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_services_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_agent_proto_rawDesc), len(file_schemas_greyseal_v1_services_agent_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_services_agent_proto_rawDescData
}

var file_schemas_greyseal_v1_services_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_schemas_greyseal_v1_services_agent_proto_goTypes = []any{
	(*RunAgentTaskRequest)(nil),   // 0: schemas.greyseal.services.v1.RunAgentTaskRequest
	(*RunAgentTaskResponse)(nil),  // 1: schemas.greyseal.services.v1.RunAgentTaskResponse
	(*GetAgentRunRequest)(nil),    // 2: schemas.greyseal.services.v1.GetAgentRunRequest
	(*GetAgentRunResponse)(nil),   // 3: schemas.greyseal.services.v1.GetAgentRunResponse
	(*ListAgentRunsRequest)(nil),  // 4: schemas.greyseal.services.v1.ListAgentRunsRequest
	(*ListAgentRunsResponse)(nil), // 5: schemas.greyseal.services.v1.ListAgentRunsResponse
	(*StreamAgentRunRequest)(nil), // 6: schemas.greyseal.services.v1.StreamAgentRunRequest
	(*AgentRunEvent)(nil),         // 7: schemas.greyseal.services.v1.AgentRunEvent
	(*v1.AgentRun)(nil),           // 8: schemas.greyseal.v1.AgentRun
}
var file_schemas_greyseal_v1_services_agent_proto_depIdxs = []int32{
	8, // 0: schemas.greyseal.services.v1.RunAgentTaskResponse.data:type_name -> schemas.greyseal.v1.AgentRun
	8, // 1: schemas.greyseal.services.v1.GetAgentRunResponse.data:type_name -> schemas.greyseal.v1.AgentRun
	8, // 2: schemas.greyseal.services.v1.ListAgentRunsResponse.data:type_name -> schemas.greyseal.v1.AgentRun
	0, // 3: schemas.greyseal.services.v1.AgentService.RunAgentTask:input_type -> schemas.greyseal.services.v1.RunAgentTaskRequest
	2, // 4: schemas.greyseal.services.v1.AgentService.GetAgentRun:input_type -> schemas.greyseal.services.v1.GetAgentRunRequest
	4, // 5: schemas.greyseal.services.v1.AgentService.ListAgentRuns:input_type -> schemas.greyseal.services.v1.ListAgentRunsRequest
	6, // 6: schemas.greyseal.services.v1.AgentService.StreamAgentRun:input_type -> schemas.greyseal.services.v1.StreamAgentRunRequest
	1, // 7: schemas.greyseal.services.v1.AgentService.RunAgentTask:output_type -> schemas.greyseal.services.v1.RunAgentTaskResponse
	3, // 8: schemas.greyseal.services.v1.AgentService.GetAgentRun:output_type -> schemas.greyseal.services.v1.GetAgentRunResponse
	5, // 9: schemas.greyseal.services.v1.AgentService.ListAgentRuns:output_type -> schemas.greyseal.services.v1.ListAgentRunsResponse
	7, // 10: schemas.greyseal.services.v1.AgentService.StreamAgentRun:output_type -> schemas.greyseal.services.v1.AgentRunEvent
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_services_agent_proto_init() }
func file_schemas_greyseal_v1_services_agent_proto_init() {
	if File_schemas_greyseal_v1_services_agent_proto != nil {
		return
	}
	file_schemas_greyseal_v1_services_agent_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_agent_proto_rawDesc), len(file_schemas_greyseal_v1_services_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_greyseal_v1_services_agent_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_services_agent_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_services_agent_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_services_agent_proto = out.File
	file_schemas_greyseal_v1_services_agent_proto_goTypes = nil
	file_schemas_greyseal_v1_services_agent_proto_depIdxs = nil
}
