// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: schemas/greyseal/v1/services/agent.proto

package servicesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RunAgentTask_FullMethodName   = "/schemas.greyseal.services.v1.AgentService/RunAgentTask"
	AgentService_GetAgentRun_FullMethodName    = "/schemas.greyseal.services.v1.AgentService/GetAgentRun"
	AgentService_StreamAgentRun_FullMethodName = "/schemas.greyseal.services.v1.AgentService/StreamAgentRun"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// RunAgentTask starts a new agentic coding-task run and returns
	// immediately with its initial state; the run continues asynchronously on
	// the provider's side.
	RunAgentTask(ctx context.Context, in *RunAgentTaskRequest, opts ...grpc.CallOption) (*RunAgentTaskResponse, error)
	// GetAgentRun returns the current state of a previously started run.
	GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*GetAgentRunResponse, error)
	// StreamAgentRun streams events for a run as they occur, until the run
	// reaches a terminal status.
	StreamAgentRun(ctx context.Context, in *StreamAgentRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentRunEvent], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RunAgentTask(ctx context.Context, in *RunAgentTaskRequest, opts ...grpc.CallOption) (*RunAgentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAgentTaskResponse)
	err := c.cc.Invoke(ctx, AgentService_RunAgentTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgentRun(ctx context.Context, in *GetAgentRunRequest, opts ...grpc.CallOption) (*GetAgentRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentRunResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamAgentRun(ctx context.Context, in *StreamAgentRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentRunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamAgentRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAgentRunRequest, AgentRunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamAgentRunClient = grpc.ServerStreamingClient[AgentRunEvent]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// RunAgentTask starts a new agentic coding-task run and returns
	// immediately with its initial state; the run continues asynchronously on
	// the provider's side.
	RunAgentTask(context.Context, *RunAgentTaskRequest) (*RunAgentTaskResponse, error)
	// GetAgentRun returns the current state of a previously started run.
	GetAgentRun(context.Context, *GetAgentRunRequest) (*GetAgentRunResponse, error)
	// StreamAgentRun streams events for a run as they occur, until the run
	// reaches a terminal status.
	StreamAgentRun(*StreamAgentRunRequest, grpc.ServerStreamingServer[AgentRunEvent]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RunAgentTask(context.Context, *RunAgentTaskRequest) (*RunAgentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAgentTask not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentRun(context.Context, *GetAgentRunRequest) (*GetAgentRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentRun not implemented")
}
func (UnimplementedAgentServiceServer) StreamAgentRun(*StreamAgentRunRequest, grpc.ServerStreamingServer[AgentRunEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamAgentRun not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RunAgentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAgentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RunAgentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RunAgentTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RunAgentTask(ctx, req.(*RunAgentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentRun(ctx, req.(*GetAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamAgentRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamAgentRun(m, &grpc.GenericServerStream[StreamAgentRunRequest, AgentRunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamAgentRunServer = grpc.ServerStreamingServer[AgentRunEvent]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemas.greyseal.services.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunAgentTask",
			Handler:    _AgentService_RunAgentTask_Handler,
		},
		{
			MethodName: "GetAgentRun",
			Handler:    _AgentService_GetAgentRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAgentRun",
			Handler:       _AgentService_StreamAgentRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "schemas/greyseal/v1/services/agent.proto",
}
