// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schemas/greyseal/v1/services/conversation.proto

package servicesv1

import (
	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// title is optional; left blank it can be auto-generated after the first exchange.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// role_uuid optionally assigns a Role system prompt to this conversation.
	RoleUuid string `protobuf:"bytes,2,opt,name=role_uuid,json=roleUuid,proto3" json:"role_uuid,omitempty"`
	// resource_uuids optionally scopes retrieval to specific resources.
	ResourceUuids []string `protobuf:"bytes,3,rep,name=resource_uuids,json=resourceUuids,proto3" json:"resource_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConversationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateConversationRequest) GetRoleUuid() string {
	if x != nil {
		return x.RoleUuid
	}
	return ""
}

func (x *CreateConversationRequest) GetResourceUuids() []string {
	if x != nil {
		return x.ResourceUuids
	}
	return nil
}

type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Conversation       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConversationResponse) GetData() *v1.Conversation {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *GetConversationRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Conversation       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *GetConversationResponse) GetData() *v1.Conversation {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *int32                 `protobuf:"varint,1,opt,name=count,proto3,oneof" json:"count,omitempty"`
	Cursor        *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *ListConversationsRequest) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *ListConversationsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListConversationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returns conversations without their messages for efficiency.
	Data          []*v1.Conversation `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Cursor        string             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Count         int32              `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversationsResponse) GetData() []*v1.Conversation {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListConversationsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListConversationsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateConversationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Fields that can be mutated after creation.
	Title         *string  `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	RoleUuid      *string  `protobuf:"bytes,3,opt,name=role_uuid,json=roleUuid,proto3,oneof" json:"role_uuid,omitempty"`
	ResourceUuids []string `protobuf:"bytes,4,rep,name=resource_uuids,json=resourceUuids,proto3" json:"resource_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationRequest) Reset() {
	*x = UpdateConversationRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationRequest) ProtoMessage() {}

func (x *UpdateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConversationRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateConversationRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateConversationRequest) GetRoleUuid() string {
	if x != nil && x.RoleUuid != nil {
		return *x.RoleUuid
	}
	return ""
}

func (x *UpdateConversationRequest) GetResourceUuids() []string {
	if x != nil {
		return x.ResourceUuids
	}
	return nil
}

type UpdateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Conversation       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationResponse) Reset() {
	*x = UpdateConversationResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationResponse) ProtoMessage() {}

func (x *UpdateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationResponse.ProtoReflect.Descriptor instead.
func (*UpdateConversationResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConversationResponse) GetData() *v1.Conversation {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteConversationRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResponse) Reset() {
	*x = DeleteConversationResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResponse) ProtoMessage() {}

func (x *DeleteConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{9}
}

type ChatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationUuid string                 `protobuf:"bytes,1,opt,name=conversation_uuid,json=conversationUuid,proto3" json:"conversation_uuid,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *ChatRequest) GetConversationUuid() string {
	if x != nil {
		return x.ConversationUuid
	}
	return ""
}

func (x *ChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatResponse is streamed; each message carries one token or chunk of content.
// The final message in the stream includes the fully-populated Message with
// resource references and uuid set.
type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// final_message is populated only on the last streamed response.
	FinalMessage  *v1.Message `protobuf:"bytes,2,opt,name=final_message,json=finalMessage,proto3" json:"final_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *ChatResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatResponse) GetFinalMessage() *v1.Message {
	if x != nil {
		return x.FinalMessage
	}
	return nil
}

type SubmitFeedbackRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MessageUuid string                 `protobuf:"bytes,1,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	// feedback: -1 negative, 0 neutral, 1 positive.
	Feedback      int32 `protobuf:"varint,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackRequest) Reset() {
	*x = SubmitFeedbackRequest{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackRequest) ProtoMessage() {}

func (x *SubmitFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitFeedbackRequest) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *SubmitFeedbackRequest) GetFeedback() int32 {
	if x != nil {
		return x.Feedback
	}
	return 0
}

type SubmitFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackResponse) Reset() {
	*x = SubmitFeedbackResponse{}
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackResponse) ProtoMessage() {}

func (x *SubmitFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP(), []int{13}
}

var File_schemas_greyseal_v1_services_conversation_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_services_conversation_proto_rawDesc = "" +
	"\n" +
	"/schemas/greyseal/v1/services/conversation.proto\x12\x1cschemas.greyseal.services.v1\x1a&schemas/greyseal/v1/conversation.proto\"u\n" +
	"\x19CreateConversationRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\trole_uuid\x18\x02 \x01(\tR\broleUuid\x12%\n" +
	"\x0eresource_uuids\x18\x03 \x03(\tR\rresourceUuids\"S\n" +
	"\x1aCreateConversationResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.schemas.greyseal.v1.ConversationR\x04data\",\n" +
	"\x16GetConversationRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"P\n" +
	"\x17GetConversationResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.schemas.greyseal.v1.ConversationR\x04data\"g\n" +
	"\x18ListConversationsRequest\x12\x19\n" +
	"\x05count\x18\x01 \x01(\x05H\x00R\x05count\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_countB\t\n" +
	"\a_cursor\"\x80\x01\n" +
	"\x19ListConversationsResponse\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.schemas.greyseal.v1.ConversationR\x04data\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xab\x01\n" +
	"\x19UpdateConversationRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12 \n" +
	"\trole_uuid\x18\x03 \x01(\tH\x01R\broleUuid\x88\x01\x01\x12%\n" +
	"\x0eresource_uuids\x18\x04 \x03(\tR\rresourceUuidsB\b\n" +
	"\x06_titleB\f\n" +
	"\n" +
	"_role_uuid\"S\n" +
	"\x1aUpdateConversationResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.schemas.greyseal.v1.ConversationR\x04data\"/\n" +
	"\x19DeleteConversationRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x1c\n" +
	"\x1aDeleteConversationResponse\"T\n" +
	"\vChatRequest\x12+\n" +
	"\x11conversation_uuid\x18\x01 \x01(\tR\x10conversationUuid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"g\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12A\n" +
	"\rfinal_message\x18\x02 \x01(\v2\x1c.schemas.greyseal.v1.MessageR\ffinalMessage\"V\n" +
	"\x15SubmitFeedbackRequest\x12!\n" +
	"\fmessage_uuid\x18\x01 \x01(\tR\vmessageUuid\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\x05R\bfeedback\"\x18\n" +
	"\x16SubmitFeedbackResponse2\xa7\a\n" +
	"\x13ConversationService\x12\x89\x01\n" +
	"\x12CreateConversation\x127.schemas.greyseal.services.v1.CreateConversationRequest\x1a8.schemas.greyseal.services.v1.CreateConversationResponse\"\x00\x12\x80\x01\n" +
	"\x0fGetConversation\x124.schemas.greyseal.services.v1.GetConversationRequest\x1a5.schemas.greyseal.services.v1.GetConversationResponse\"\x00\x12\x86\x01\n" +
	"\x11ListConversations\x126.schemas.greyseal.services.v1.ListConversationsRequest\x1a7.schemas.greyseal.services.v1.ListConversationsResponse\"\x00\x12\x89\x01\n" +
	"\x12UpdateConversation\x127.schemas.greyseal.services.v1.UpdateConversationRequest\x1a8.schemas.greyseal.services.v1.UpdateConversationResponse\"\x00\x12\x89\x01\n" +
	"\x12DeleteConversation\x127.schemas.greyseal.services.v1.DeleteConversationRequest\x1a8.schemas.greyseal.services.v1.DeleteConversationResponse\"\x00\x12a\n" +
	"\x04Chat\x12).schemas.greyseal.services.v1.ChatRequest\x1a*.schemas.greyseal.services.v1.ChatResponse\"\x000\x01\x12}\n" +
	"\x0eSubmitFeedback\x123.schemas.greyseal.services.v1.SubmitFeedbackRequest\x1a4.schemas.greyseal.services.v1.SubmitFeedbackResponse\"\x00B\x93\x02\n" +
	" com.schemas.greyseal.services.v1B\x11ConversationProtoP\x01ZIgithub.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services;servicesv1\xa2\x02\x03SGS\xaa\x02\x1cSchemas.Greyseal.Services.V1\xca\x02\x1cSchemas\\Greyseal\\Services\\V1\xe2\x02(Schemas\\Greyseal\\Services\\V1\\GPBMetadata\xea\x02\x1fSchemas::Greyseal::Services::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_services_conversation_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_services_conversation_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_services_conversation_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_services_conversation_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_services_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_conversation_proto_rawDesc), len(file_schemas_greyseal_v1_services_conversation_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_services_conversation_proto_rawDescData
}

var file_schemas_greyseal_v1_services_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_schemas_greyseal_v1_services_conversation_proto_goTypes = []any{
	(*CreateConversationRequest)(nil),  // 0: schemas.greyseal.services.v1.CreateConversationRequest
	(*CreateConversationResponse)(nil), // 1: schemas.greyseal.services.v1.CreateConversationResponse
	(*GetConversationRequest)(nil),     // 2: schemas.greyseal.services.v1.GetConversationRequest
	(*GetConversationResponse)(nil),    // 3: schemas.greyseal.services.v1.GetConversationResponse
	(*ListConversationsRequest)(nil),   // 4: schemas.greyseal.services.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil),  // 5: schemas.greyseal.services.v1.ListConversationsResponse
	(*UpdateConversationRequest)(nil),  // 6: schemas.greyseal.services.v1.UpdateConversationRequest
	(*UpdateConversationResponse)(nil), // 7: schemas.greyseal.services.v1.UpdateConversationResponse
	(*DeleteConversationRequest)(nil),  // 8: schemas.greyseal.services.v1.DeleteConversationRequest
	(*DeleteConversationResponse)(nil), // 9: schemas.greyseal.services.v1.DeleteConversationResponse
	(*ChatRequest)(nil),                // 10: schemas.greyseal.services.v1.ChatRequest
	(*ChatResponse)(nil),               // 11: schemas.greyseal.services.v1.ChatResponse
	(*SubmitFeedbackRequest)(nil),      // 12: schemas.greyseal.services.v1.SubmitFeedbackRequest
	(*SubmitFeedbackResponse)(nil),     // 13: schemas.greyseal.services.v1.SubmitFeedbackResponse
	(*v1.Conversation)(nil),            // 14: schemas.greyseal.v1.Conversation
	(*v1.Message)(nil),                 // 15: schemas.greyseal.v1.Message
}
var file_schemas_greyseal_v1_services_conversation_proto_depIdxs = []int32{
	14, // 0: schemas.greyseal.services.v1.CreateConversationResponse.data:type_name -> schemas.greyseal.v1.Conversation
	14, // 1: schemas.greyseal.services.v1.GetConversationResponse.data:type_name -> schemas.greyseal.v1.Conversation
	14, // 2: schemas.greyseal.services.v1.ListConversationsResponse.data:type_name -> schemas.greyseal.v1.Conversation
	14, // 3: schemas.greyseal.services.v1.UpdateConversationResponse.data:type_name -> schemas.greyseal.v1.Conversation
	15, // 4: schemas.greyseal.services.v1.ChatResponse.final_message:type_name -> schemas.greyseal.v1.Message
	0,  // 5: schemas.greyseal.services.v1.ConversationService.CreateConversation:input_type -> schemas.greyseal.services.v1.CreateConversationRequest
	2,  // 6: schemas.greyseal.services.v1.ConversationService.GetConversation:input_type -> schemas.greyseal.services.v1.GetConversationRequest
	4,  // 7: schemas.greyseal.services.v1.ConversationService.ListConversations:input_type -> schemas.greyseal.services.v1.ListConversationsRequest
	6,  // 8: schemas.greyseal.services.v1.ConversationService.UpdateConversation:input_type -> schemas.greyseal.services.v1.UpdateConversationRequest
	8,  // 9: schemas.greyseal.services.v1.ConversationService.DeleteConversation:input_type -> schemas.greyseal.services.v1.DeleteConversationRequest
	10, // 10: schemas.greyseal.services.v1.ConversationService.Chat:input_type -> schemas.greyseal.services.v1.ChatRequest
	12, // 11: schemas.greyseal.services.v1.ConversationService.SubmitFeedback:input_type -> schemas.greyseal.services.v1.SubmitFeedbackRequest
	1,  // 12: schemas.greyseal.services.v1.ConversationService.CreateConversation:output_type -> schemas.greyseal.services.v1.CreateConversationResponse
	3,  // 13: schemas.greyseal.services.v1.ConversationService.GetConversation:output_type -> schemas.greyseal.services.v1.GetConversationResponse
	5,  // 14: schemas.greyseal.services.v1.ConversationService.ListConversations:output_type -> schemas.greyseal.services.v1.ListConversationsResponse
	7,  // 15: schemas.greyseal.services.v1.ConversationService.UpdateConversation:output_type -> schemas.greyseal.services.v1.UpdateConversationResponse
	9,  // 16: schemas.greyseal.services.v1.ConversationService.DeleteConversation:output_type -> schemas.greyseal.services.v1.DeleteConversationResponse
	11, // 17: schemas.greyseal.services.v1.ConversationService.Chat:output_type -> schemas.greyseal.services.v1.ChatResponse
	13, // 18: schemas.greyseal.services.v1.ConversationService.SubmitFeedback:output_type -> schemas.greyseal.services.v1.SubmitFeedbackResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_services_conversation_proto_init() }
func file_schemas_greyseal_v1_services_conversation_proto_init() {
	if File_schemas_greyseal_v1_services_conversation_proto != nil {
		return
	}
	file_schemas_greyseal_v1_services_conversation_proto_msgTypes[4].OneofWrappers = []any{}
	file_schemas_greyseal_v1_services_conversation_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_conversation_proto_rawDesc), len(file_schemas_greyseal_v1_services_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_greyseal_v1_services_conversation_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_services_conversation_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_services_conversation_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_services_conversation_proto = out.File
	file_schemas_greyseal_v1_services_conversation_proto_goTypes = nil
	file_schemas_greyseal_v1_services_conversation_proto_depIdxs = nil
}
