// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: schemas/greyseal/v1/services/draft.proto

package servicesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DraftService_DraftDocument_FullMethodName = "/schemas.greyseal.services.v1.DraftService/DraftDocument"
)

// DraftServiceClient is the client API for DraftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DraftService writes first drafts of planning documents — discovery docs
// and designs — in the house templates, from source material the caller
// supplies. It never stores anything: the caller reviews the draft and saves
// it to the owning service (narwhal, rabbit).
type DraftServiceClient interface {
	// DraftDocument streams the draft's markdown as it is generated. The final
	// message has done=true and carries the full body, plus proposed specs
	// parsed from a design's "Domain objects" section.
	DraftDocument(ctx context.Context, in *DraftDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DraftDocumentChunk], error)
}

type draftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDraftServiceClient(cc grpc.ClientConnInterface) DraftServiceClient {
	return &draftServiceClient{cc}
}

func (c *draftServiceClient) DraftDocument(ctx context.Context, in *DraftDocumentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DraftDocumentChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DraftService_ServiceDesc.Streams[0], DraftService_DraftDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DraftDocumentRequest, DraftDocumentChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DraftService_DraftDocumentClient = grpc.ServerStreamingClient[DraftDocumentChunk]

// DraftServiceServer is the server API for DraftService service.
// All implementations must embed UnimplementedDraftServiceServer
// for forward compatibility.
//
// DraftService writes first drafts of planning documents — discovery docs
// and designs — in the house templates, from source material the caller
// supplies. It never stores anything: the caller reviews the draft and saves
// it to the owning service (narwhal, rabbit).
type DraftServiceServer interface {
	// DraftDocument streams the draft's markdown as it is generated. The final
	// message has done=true and carries the full body, plus proposed specs
	// parsed from a design's "Domain objects" section.
	DraftDocument(*DraftDocumentRequest, grpc.ServerStreamingServer[DraftDocumentChunk]) error
	mustEmbedUnimplementedDraftServiceServer()
}

// UnimplementedDraftServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDraftServiceServer struct{}

func (UnimplementedDraftServiceServer) DraftDocument(*DraftDocumentRequest, grpc.ServerStreamingServer[DraftDocumentChunk]) error {
	return status.Error(codes.Unimplemented, "method DraftDocument not implemented")
}
func (UnimplementedDraftServiceServer) mustEmbedUnimplementedDraftServiceServer() {}
func (UnimplementedDraftServiceServer) testEmbeddedByValue()                      {}

// UnsafeDraftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DraftServiceServer will
// result in compilation errors.
type UnsafeDraftServiceServer interface {
	mustEmbedUnimplementedDraftServiceServer()
}

func RegisterDraftServiceServer(s grpc.ServiceRegistrar, srv DraftServiceServer) {
	// If the following call panics, it indicates UnimplementedDraftServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DraftService_ServiceDesc, srv)
}

func _DraftService_DraftDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DraftDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DraftServiceServer).DraftDocument(m, &grpc.GenericServerStream[DraftDocumentRequest, DraftDocumentChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DraftService_DraftDocumentServer = grpc.ServerStreamingServer[DraftDocumentChunk]

// DraftService_ServiceDesc is the grpc.ServiceDesc for DraftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DraftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schemas.greyseal.services.v1.DraftService",
	HandlerType: (*DraftServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DraftDocument",
			Handler:       _DraftService_DraftDocument_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "schemas/greyseal/v1/services/draft.proto",
}
