// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: schemas/greyseal/v1/services/draft.proto

package servicesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DraftKind int32

const (
	DraftKind_DRAFT_KIND_UNSPECIFIED DraftKind = 0
	DraftKind_DRAFT_KIND_DISCOVERY   DraftKind = 1
	DraftKind_DRAFT_KIND_DESIGN      DraftKind = 2
)

// Enum value maps for DraftKind.
var (
	DraftKind_name = map[int32]string{
		0: "DRAFT_KIND_UNSPECIFIED",
		1: "DRAFT_KIND_DISCOVERY",
		2: "DRAFT_KIND_DESIGN",
	}
	DraftKind_value = map[string]int32{
		"DRAFT_KIND_UNSPECIFIED": 0,
		"DRAFT_KIND_DISCOVERY":   1,
		"DRAFT_KIND_DESIGN":      2,
	}
)

func (x DraftKind) Enum() *DraftKind {
	p := new(DraftKind)
	*p = x
	return p
}

func (x DraftKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DraftKind) Descriptor() protoreflect.EnumDescriptor {
	return file_schemas_greyseal_v1_services_draft_proto_enumTypes[0].Descriptor()
}

func (DraftKind) Type() protoreflect.EnumType {
	return &file_schemas_greyseal_v1_services_draft_proto_enumTypes[0]
}

func (x DraftKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DraftKind.Descriptor instead.
func (DraftKind) EnumDescriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_draft_proto_rawDescGZIP(), []int{0}
}

type DraftDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  DraftKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=schemas.greyseal.services.v1.DraftKind" json:"kind,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// source is the material to draft from, as markdown: the originating
	// request, the parent discovery doc, the product's system doc.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// current is the draft's existing body, if any, to improve on rather
	// than start over.
	Current       string `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftDocumentRequest) Reset() {
	*x = DraftDocumentRequest{}
	mi := &file_schemas_greyseal_v1_services_draft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftDocumentRequest) ProtoMessage() {}

func (x *DraftDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_draft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftDocumentRequest.ProtoReflect.Descriptor instead.
func (*DraftDocumentRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_draft_proto_rawDescGZIP(), []int{0}
}

func (x *DraftDocumentRequest) GetKind() DraftKind {
	if x != nil {
		return x.Kind
	}
	return DraftKind_DRAFT_KIND_UNSPECIFIED
}

func (x *DraftDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DraftDocumentRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DraftDocumentRequest) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

// ProposedSpec is one domain object from a design draft's "Domain objects"
// table — the machine-readable input rabbit Specs are created from.
type ProposedSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// operation: "create" | "modify" | "deprecate".
	Operation string `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// depends_on names other proposed specs in the same draft.
	DependsOn     []string `protobuf:"bytes,3,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposedSpec) Reset() {
	*x = ProposedSpec{}
	mi := &file_schemas_greyseal_v1_services_draft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposedSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposedSpec) ProtoMessage() {}

func (x *ProposedSpec) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_draft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposedSpec.ProtoReflect.Descriptor instead.
func (*ProposedSpec) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_draft_proto_rawDescGZIP(), []int{1}
}

func (x *ProposedSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProposedSpec) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ProposedSpec) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type DraftDocumentChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the next piece of markdown; empty on the final message.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Done  bool   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	// body is the complete draft, set on the final message only.
	Body          string          `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Specs         []*ProposedSpec `protobuf:"bytes,4,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftDocumentChunk) Reset() {
	*x = DraftDocumentChunk{}
	mi := &file_schemas_greyseal_v1_services_draft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftDocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftDocumentChunk) ProtoMessage() {}

func (x *DraftDocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_draft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftDocumentChunk.ProtoReflect.Descriptor instead.
func (*DraftDocumentChunk) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_draft_proto_rawDescGZIP(), []int{2}
}

func (x *DraftDocumentChunk) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DraftDocumentChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *DraftDocumentChunk) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DraftDocumentChunk) GetSpecs() []*ProposedSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

var File_schemas_greyseal_v1_services_draft_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_services_draft_proto_rawDesc = "" +
	"\n" +
	"(schemas/greyseal/v1/services/draft.proto\x12\x1cschemas.greyseal.services.v1\"\x9b\x01\n" +
	"\x14DraftDocumentRequest\x12;\n" +
	"\x04kind\x18\x01 \x01(\x0e2'.schemas.greyseal.services.v1.DraftKindR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\tR\acurrent\"_\n" +
	"\fProposedSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\tR\tdependsOn\"\x94\x01\n" +
	"\x12DraftDocumentChunk\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12@\n" +
	"\x05specs\x18\x04 \x03(\v2*.schemas.greyseal.services.v1.ProposedSpecR\x05specs*X\n" +
	"\tDraftKind\x12\x1a\n" +
	"\x16DRAFT_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DRAFT_KIND_DISCOVERY\x10\x01\x12\x15\n" +
	"\x11DRAFT_KIND_DESIGN\x10\x022\x89\x01\n" +
	"\fDraftService\x12y\n" +
	"\rDraftDocument\x122.schemas.greyseal.services.v1.DraftDocumentRequest\x1a0.schemas.greyseal.services.v1.DraftDocumentChunk\"\x000\x01B\x8c\x02\n" +
	" com.schemas.greyseal.services.v1B\n" +
	"DraftProtoP\x01ZIgithub.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services;servicesv1\xa2\x02\x03SGS\xaa\x02\x1cSchemas.Greyseal.Services.V1\xca\x02\x1cSchemas\\Greyseal\\Services\\V1\xe2\x02(Schemas\\Greyseal\\Services\\V1\\GPBMetadata\xea\x02\x1fSchemas::Greyseal::Services::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_services_draft_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_services_draft_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_services_draft_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_services_draft_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_services_draft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_draft_proto_rawDesc), len(file_schemas_greyseal_v1_services_draft_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_services_draft_proto_rawDescData
}

var file_schemas_greyseal_v1_services_draft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemas_greyseal_v1_services_draft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schemas_greyseal_v1_services_draft_proto_goTypes = []any{
	(DraftKind)(0),               // 0: schemas.greyseal.services.v1.DraftKind
	(*DraftDocumentRequest)(nil), // 1: schemas.greyseal.services.v1.DraftDocumentRequest
	(*ProposedSpec)(nil),         // 2: schemas.greyseal.services.v1.ProposedSpec
	(*DraftDocumentChunk)(nil),   // 3: schemas.greyseal.services.v1.DraftDocumentChunk
}
var file_schemas_greyseal_v1_services_draft_proto_depIdxs = []int32{
	0, // 0: schemas.greyseal.services.v1.DraftDocumentRequest.kind:type_name -> schemas.greyseal.services.v1.DraftKind
	2, // 1: schemas.greyseal.services.v1.DraftDocumentChunk.specs:type_name -> schemas.greyseal.services.v1.ProposedSpec
	1, // 2: schemas.greyseal.services.v1.DraftService.DraftDocument:input_type -> schemas.greyseal.services.v1.DraftDocumentRequest
	3, // 3: schemas.greyseal.services.v1.DraftService.DraftDocument:output_type -> schemas.greyseal.services.v1.DraftDocumentChunk
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_services_draft_proto_init() }
func file_schemas_greyseal_v1_services_draft_proto_init() {
	if File_schemas_greyseal_v1_services_draft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_draft_proto_rawDesc), len(file_schemas_greyseal_v1_services_draft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_greyseal_v1_services_draft_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_services_draft_proto_depIdxs,
		EnumInfos:         file_schemas_greyseal_v1_services_draft_proto_enumTypes,
		MessageInfos:      file_schemas_greyseal_v1_services_draft_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_services_draft_proto = out.File
	file_schemas_greyseal_v1_services_draft_proto_goTypes = nil
	file_schemas_greyseal_v1_services_draft_proto_depIdxs = nil
}
