// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: schemas/greyseal/v1/services/question.proto

package servicesv1

import (
	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *int32                 `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsRequest) Reset() {
	*x = ListQuestionsRequest{}
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsRequest) ProtoMessage() {}

func (x *ListQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_question_proto_rawDescGZIP(), []int{0}
}

func (x *ListQuestionsRequest) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *ListQuestionsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v1.Question         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsResponse) Reset() {
	*x = ListQuestionsResponse{}
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsResponse) ProtoMessage() {}

func (x *ListQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_question_proto_rawDescGZIP(), []int{1}
}

func (x *ListQuestionsResponse) GetData() []*v1.Question {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListQuestionsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListQuestionsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_question_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuestionRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Question           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionResponse) Reset() {
	*x = GetQuestionResponse{}
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionResponse) ProtoMessage() {}

func (x *GetQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionResponse.ProtoReflect.Descriptor instead.
func (*GetQuestionResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_question_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuestionResponse) GetData() *v1.Question {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Question           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_question_proto_rawDescGZIP(), []int{4}
}

func (x *CreateQuestionRequest) GetData() *v1.Question {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Answer             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_question_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQuestionResponse) GetData() *v1.Answer {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_schemas_greyseal_v1_services_question_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_services_question_proto_rawDesc = "" +
	"\n" +
	"+schemas/greyseal/v1/services/question.proto\x12\x1fschemas.greyseal.v1.services.v1\x1a\"schemas/greyseal/v1/question.proto\"c\n" +
	"\x14ListQuestionsRequest\x12\x19\n" +
	"\x05count\x18\x02 \x01(\x05H\x00R\x05count\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_countB\t\n" +
	"\a_cursor\"x\n" +
	"\x15ListQuestionsResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.schemas.greyseal.v1.QuestionR\x04data\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"(\n" +
	"\x12GetQuestionRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"H\n" +
	"\x13GetQuestionResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.QuestionR\x04data\"J\n" +
	"\x15CreateQuestionRequest\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.QuestionR\x04data\"I\n" +
	"\x16CreateQuestionResponse\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.schemas.greyseal.v1.AnswerR\x04data2\x96\x03\n" +
	"\x0fQuestionService\x12\x80\x01\n" +
	"\rListQuestions\x125.schemas.greyseal.v1.services.v1.ListQuestionsRequest\x1a6.schemas.greyseal.v1.services.v1.ListQuestionsResponse\"\x00\x12z\n" +
	"\vGetQuestion\x123.schemas.greyseal.v1.services.v1.GetQuestionRequest\x1a4.schemas.greyseal.v1.services.v1.GetQuestionResponse\"\x00\x12\x83\x01\n" +
	"\x0eCreateQuestion\x126.schemas.greyseal.v1.services.v1.CreateQuestionRequest\x1a7.schemas.greyseal.v1.services.v1.CreateQuestionResponse\"\x00B\xa0\x02\n" +
	"#com.schemas.greyseal.v1.services.v1B\rQuestionProtoP\x01ZIgithub.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services;servicesv1\xa2\x02\x04SGVS\xaa\x02\x1fSchemas.Greyseal.V1.Services.V1\xca\x02\x1fSchemas\\Greyseal\\V1\\Services\\V1\xe2\x02+Schemas\\Greyseal\\V1\\Services\\V1\\GPBMetadata\xea\x02#Schemas::Greyseal::V1::Services::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_services_question_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_services_question_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_services_question_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_services_question_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_services_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_question_proto_rawDesc), len(file_schemas_greyseal_v1_services_question_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_services_question_proto_rawDescData
}

var file_schemas_greyseal_v1_services_question_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_schemas_greyseal_v1_services_question_proto_goTypes = []any{
	(*ListQuestionsRequest)(nil),   // 0: schemas.greyseal.v1.services.v1.ListQuestionsRequest
	(*ListQuestionsResponse)(nil),  // 1: schemas.greyseal.v1.services.v1.ListQuestionsResponse
	(*GetQuestionRequest)(nil),     // 2: schemas.greyseal.v1.services.v1.GetQuestionRequest
	(*GetQuestionResponse)(nil),    // 3: schemas.greyseal.v1.services.v1.GetQuestionResponse
	(*CreateQuestionRequest)(nil),  // 4: schemas.greyseal.v1.services.v1.CreateQuestionRequest
	(*CreateQuestionResponse)(nil), // 5: schemas.greyseal.v1.services.v1.CreateQuestionResponse
	(*v1.Question)(nil),            // 6: schemas.greyseal.v1.Question
	(*v1.Answer)(nil),              // 7: schemas.greyseal.v1.Answer
}
var file_schemas_greyseal_v1_services_question_proto_depIdxs = []int32{
	6, // 0: schemas.greyseal.v1.services.v1.ListQuestionsResponse.data:type_name -> schemas.greyseal.v1.Question
	6, // 1: schemas.greyseal.v1.services.v1.GetQuestionResponse.data:type_name -> schemas.greyseal.v1.Question
	6, // 2: schemas.greyseal.v1.services.v1.CreateQuestionRequest.data:type_name -> schemas.greyseal.v1.Question
	7, // 3: schemas.greyseal.v1.services.v1.CreateQuestionResponse.data:type_name -> schemas.greyseal.v1.Answer
	0, // 4: schemas.greyseal.v1.services.v1.QuestionService.ListQuestions:input_type -> schemas.greyseal.v1.services.v1.ListQuestionsRequest
	2, // 5: schemas.greyseal.v1.services.v1.QuestionService.GetQuestion:input_type -> schemas.greyseal.v1.services.v1.GetQuestionRequest
	4, // 6: schemas.greyseal.v1.services.v1.QuestionService.CreateQuestion:input_type -> schemas.greyseal.v1.services.v1.CreateQuestionRequest
	1, // 7: schemas.greyseal.v1.services.v1.QuestionService.ListQuestions:output_type -> schemas.greyseal.v1.services.v1.ListQuestionsResponse
	3, // 8: schemas.greyseal.v1.services.v1.QuestionService.GetQuestion:output_type -> schemas.greyseal.v1.services.v1.GetQuestionResponse
	5, // 9: schemas.greyseal.v1.services.v1.QuestionService.CreateQuestion:output_type -> schemas.greyseal.v1.services.v1.CreateQuestionResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_services_question_proto_init() }
func file_schemas_greyseal_v1_services_question_proto_init() {
	if File_schemas_greyseal_v1_services_question_proto != nil {
		return
	}
	file_schemas_greyseal_v1_services_question_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_question_proto_rawDesc), len(file_schemas_greyseal_v1_services_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_greyseal_v1_services_question_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_services_question_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_services_question_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_services_question_proto = out.File
	file_schemas_greyseal_v1_services_question_proto_goTypes = nil
	file_schemas_greyseal_v1_services_question_proto_depIdxs = nil
}
