// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: schemas/greyseal/v1/services/resource.proto

package servicesv1

import (
	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *int32                 `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ListResourcesRequest) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *ListResourcesRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v1.Resource         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ListResourcesResponse) GetData() []*v1.Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListResourcesResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListResourcesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Resource           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourceResponse) GetData() *v1.Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Resource           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResourceRequest) GetData() *v1.Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Resource           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResourceResponse) GetData() *v1.Resource {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_schemas_greyseal_v1_services_resource_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_services_resource_proto_rawDesc = "" +
	"\n" +
	"+schemas/greyseal/v1/services/resource.proto\x12\x1fschemas.greyseal.v1.services.v1\x1a\"schemas/greyseal/v1/resource.proto\"c\n" +
	"\x14ListResourcesRequest\x12\x19\n" +
	"\x05count\x18\x02 \x01(\x05H\x00R\x05count\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_countB\t\n" +
	"\a_cursor\"x\n" +
	"\x15ListResourcesResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.schemas.greyseal.v1.ResourceR\x04data\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"(\n" +
	"\x12GetResourceRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"H\n" +
	"\x13GetResourceResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.ResourceR\x04data\"J\n" +
	"\x15CreateResourceRequest\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.ResourceR\x04data\"K\n" +
	"\x16CreateResourceResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.schemas.greyseal.v1.ResourceR\x04data2\x96\x03\n" +
	"\x0fResourceService\x12\x80\x01\n" +
	"\rListResources\x125.schemas.greyseal.v1.services.v1.ListResourcesRequest\x1a6.schemas.greyseal.v1.services.v1.ListResourcesResponse\"\x00\x12z\n" +
	"\vGetResource\x123.schemas.greyseal.v1.services.v1.GetResourceRequest\x1a4.schemas.greyseal.v1.services.v1.GetResourceResponse\"\x00\x12\x83\x01\n" +
	"\x0eCreateResource\x126.schemas.greyseal.v1.services.v1.CreateResourceRequest\x1a7.schemas.greyseal.v1.services.v1.CreateResourceResponse\"\x00B\xa0\x02\n" +
	"#com.schemas.greyseal.v1.services.v1B\rResourceProtoP\x01ZIgithub.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services;servicesv1\xa2\x02\x04SGVS\xaa\x02\x1fSchemas.Greyseal.V1.Services.V1\xca\x02\x1fSchemas\\Greyseal\\V1\\Services\\V1\xe2\x02+Schemas\\Greyseal\\V1\\Services\\V1\\GPBMetadata\xea\x02#Schemas::Greyseal::V1::Services::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_services_resource_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_services_resource_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_services_resource_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_services_resource_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_services_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_resource_proto_rawDesc), len(file_schemas_greyseal_v1_services_resource_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_services_resource_proto_rawDescData
}

var file_schemas_greyseal_v1_services_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_schemas_greyseal_v1_services_resource_proto_goTypes = []any{
	(*ListResourcesRequest)(nil),   // 0: schemas.greyseal.v1.services.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),  // 1: schemas.greyseal.v1.services.v1.ListResourcesResponse
	(*GetResourceRequest)(nil),     // 2: schemas.greyseal.v1.services.v1.GetResourceRequest
	(*GetResourceResponse)(nil),    // 3: schemas.greyseal.v1.services.v1.GetResourceResponse
	(*CreateResourceRequest)(nil),  // 4: schemas.greyseal.v1.services.v1.CreateResourceRequest
	(*CreateResourceResponse)(nil), // 5: schemas.greyseal.v1.services.v1.CreateResourceResponse
	(*v1.Resource)(nil),            // 6: schemas.greyseal.v1.Resource
}
var file_schemas_greyseal_v1_services_resource_proto_depIdxs = []int32{
	6, // 0: schemas.greyseal.v1.services.v1.ListResourcesResponse.data:type_name -> schemas.greyseal.v1.Resource
	6, // 1: schemas.greyseal.v1.services.v1.GetResourceResponse.data:type_name -> schemas.greyseal.v1.Resource
	6, // 2: schemas.greyseal.v1.services.v1.CreateResourceRequest.data:type_name -> schemas.greyseal.v1.Resource
	6, // 3: schemas.greyseal.v1.services.v1.CreateResourceResponse.data:type_name -> schemas.greyseal.v1.Resource
	0, // 4: schemas.greyseal.v1.services.v1.ResourceService.ListResources:input_type -> schemas.greyseal.v1.services.v1.ListResourcesRequest
	2, // 5: schemas.greyseal.v1.services.v1.ResourceService.GetResource:input_type -> schemas.greyseal.v1.services.v1.GetResourceRequest
	4, // 6: schemas.greyseal.v1.services.v1.ResourceService.CreateResource:input_type -> schemas.greyseal.v1.services.v1.CreateResourceRequest
	1, // 7: schemas.greyseal.v1.services.v1.ResourceService.ListResources:output_type -> schemas.greyseal.v1.services.v1.ListResourcesResponse
	3, // 8: schemas.greyseal.v1.services.v1.ResourceService.GetResource:output_type -> schemas.greyseal.v1.services.v1.GetResourceResponse
	5, // 9: schemas.greyseal.v1.services.v1.ResourceService.CreateResource:output_type -> schemas.greyseal.v1.services.v1.CreateResourceResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_services_resource_proto_init() }
func file_schemas_greyseal_v1_services_resource_proto_init() {
	if File_schemas_greyseal_v1_services_resource_proto != nil {
		return
	}
	file_schemas_greyseal_v1_services_resource_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_resource_proto_rawDesc), len(file_schemas_greyseal_v1_services_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_greyseal_v1_services_resource_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_services_resource_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_services_resource_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_services_resource_proto = out.File
	file_schemas_greyseal_v1_services_resource_proto_goTypes = nil
	file_schemas_greyseal_v1_services_resource_proto_depIdxs = nil
}
