// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schemas/greyseal/v1/services/role.proto

package services

import (
	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Role               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetData() *v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Role               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleResponse) GetData() *v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Role               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleResponse) GetData() *v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *int32                 `protobuf:"varint,1,opt,name=count,proto3,oneof" json:"count,omitempty"`
	Cursor        *string                `protobuf:"bytes,2,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{4}
}

func (x *ListRolesRequest) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *ListRolesRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v1.Role             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{5}
}

func (x *ListRolesResponse) GetData() []*v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListRolesResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListRolesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Data          *v1.Role               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoleRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRoleRequest) GetData() *v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *v1.Role               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoleResponse) GetData() *v1.Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_services_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_services_role_proto_rawDescGZIP(), []int{9}
}

var File_schemas_greyseal_v1_services_role_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_services_role_proto_rawDesc = "" +
	"\n" +
	"'schemas/greyseal/v1/services/role.proto\x12\x1cschemas.greyseal.v1.services\x1a\x1eschemas/greyseal/v1/role.proto\"B\n" +
	"\x11CreateRoleRequest\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.schemas.greyseal.v1.RoleR\x04data\"C\n" +
	"\x12CreateRoleResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.schemas.greyseal.v1.RoleR\x04data\"$\n" +
	"\x0eGetRoleRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"@\n" +
	"\x0fGetRoleResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.schemas.greyseal.v1.RoleR\x04data\"_\n" +
	"\x10ListRolesRequest\x12\x19\n" +
	"\x05count\x18\x01 \x01(\x05H\x00R\x05count\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x02 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_countB\t\n" +
	"\a_cursor\"p\n" +
	"\x11ListRolesResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.schemas.greyseal.v1.RoleR\x04data\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"V\n" +
	"\x11UpdateRoleRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x19.schemas.greyseal.v1.RoleR\x04data\"C\n" +
	"\x12UpdateRoleResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.schemas.greyseal.v1.RoleR\x04data\"'\n" +
	"\x11DeleteRoleRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x14\n" +
	"\x12DeleteRoleResponse2\xc0\x04\n" +
	"\vRoleService\x12q\n" +
	"\n" +
	"CreateRole\x12/.schemas.greyseal.v1.services.CreateRoleRequest\x1a0.schemas.greyseal.v1.services.CreateRoleResponse\"\x00\x12h\n" +
	"\aGetRole\x12,.schemas.greyseal.v1.services.GetRoleRequest\x1a-.schemas.greyseal.v1.services.GetRoleResponse\"\x00\x12n\n" +
	"\tListRoles\x12..schemas.greyseal.v1.services.ListRolesRequest\x1a/.schemas.greyseal.v1.services.ListRolesResponse\"\x00\x12q\n" +
	"\n" +
	"UpdateRole\x12/.schemas.greyseal.v1.services.UpdateRoleRequest\x1a0.schemas.greyseal.v1.services.UpdateRoleResponse\"\x00\x12q\n" +
	"\n" +
	"DeleteRole\x12/.schemas.greyseal.v1.services.DeleteRoleRequest\x1a0.schemas.greyseal.v1.services.DeleteRoleResponse\"\x00B\x81\x02\n" +
	" com.schemas.greyseal.v1.servicesB\tRoleProtoP\x01Z>github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services\xa2\x02\x04SGVS\xaa\x02\x1cSchemas.Greyseal.V1.Services\xca\x02\x1cSchemas\\Greyseal\\V1\\Services\xe2\x02(Schemas\\Greyseal\\V1\\Services\\GPBMetadata\xea\x02\x1fSchemas::Greyseal::V1::Servicesb\x06proto3"

var (
	file_schemas_greyseal_v1_services_role_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_services_role_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_services_role_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_services_role_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_services_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_role_proto_rawDesc), len(file_schemas_greyseal_v1_services_role_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_services_role_proto_rawDescData
}

var file_schemas_greyseal_v1_services_role_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_schemas_greyseal_v1_services_role_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),  // 0: schemas.greyseal.v1.services.CreateRoleRequest
	(*CreateRoleResponse)(nil), // 1: schemas.greyseal.v1.services.CreateRoleResponse
	(*GetRoleRequest)(nil),     // 2: schemas.greyseal.v1.services.GetRoleRequest
	(*GetRoleResponse)(nil),    // 3: schemas.greyseal.v1.services.GetRoleResponse
	(*ListRolesRequest)(nil),   // 4: schemas.greyseal.v1.services.ListRolesRequest
	(*ListRolesResponse)(nil),  // 5: schemas.greyseal.v1.services.ListRolesResponse
	(*UpdateRoleRequest)(nil),  // 6: schemas.greyseal.v1.services.UpdateRoleRequest
	(*UpdateRoleResponse)(nil), // 7: schemas.greyseal.v1.services.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),  // 8: schemas.greyseal.v1.services.DeleteRoleRequest
	(*DeleteRoleResponse)(nil), // 9: schemas.greyseal.v1.services.DeleteRoleResponse
	(*v1.Role)(nil),            // 10: schemas.greyseal.v1.Role
}
var file_schemas_greyseal_v1_services_role_proto_depIdxs = []int32{
	10, // 0: schemas.greyseal.v1.services.CreateRoleRequest.data:type_name -> schemas.greyseal.v1.Role
	10, // 1: schemas.greyseal.v1.services.CreateRoleResponse.data:type_name -> schemas.greyseal.v1.Role
	10, // 2: schemas.greyseal.v1.services.GetRoleResponse.data:type_name -> schemas.greyseal.v1.Role
	10, // 3: schemas.greyseal.v1.services.ListRolesResponse.data:type_name -> schemas.greyseal.v1.Role
	10, // 4: schemas.greyseal.v1.services.UpdateRoleRequest.data:type_name -> schemas.greyseal.v1.Role
	10, // 5: schemas.greyseal.v1.services.UpdateRoleResponse.data:type_name -> schemas.greyseal.v1.Role
	0,  // 6: schemas.greyseal.v1.services.RoleService.CreateRole:input_type -> schemas.greyseal.v1.services.CreateRoleRequest
	2,  // 7: schemas.greyseal.v1.services.RoleService.GetRole:input_type -> schemas.greyseal.v1.services.GetRoleRequest
	4,  // 8: schemas.greyseal.v1.services.RoleService.ListRoles:input_type -> schemas.greyseal.v1.services.ListRolesRequest
	6,  // 9: schemas.greyseal.v1.services.RoleService.UpdateRole:input_type -> schemas.greyseal.v1.services.UpdateRoleRequest
	8,  // 10: schemas.greyseal.v1.services.RoleService.DeleteRole:input_type -> schemas.greyseal.v1.services.DeleteRoleRequest
	1,  // 11: schemas.greyseal.v1.services.RoleService.CreateRole:output_type -> schemas.greyseal.v1.services.CreateRoleResponse
	3,  // 12: schemas.greyseal.v1.services.RoleService.GetRole:output_type -> schemas.greyseal.v1.services.GetRoleResponse
	5,  // 13: schemas.greyseal.v1.services.RoleService.ListRoles:output_type -> schemas.greyseal.v1.services.ListRolesResponse
	7,  // 14: schemas.greyseal.v1.services.RoleService.UpdateRole:output_type -> schemas.greyseal.v1.services.UpdateRoleResponse
	9,  // 15: schemas.greyseal.v1.services.RoleService.DeleteRole:output_type -> schemas.greyseal.v1.services.DeleteRoleResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_services_role_proto_init() }
func file_schemas_greyseal_v1_services_role_proto_init() {
	if File_schemas_greyseal_v1_services_role_proto != nil {
		return
	}
	file_schemas_greyseal_v1_services_role_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_services_role_proto_rawDesc), len(file_schemas_greyseal_v1_services_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_greyseal_v1_services_role_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_services_role_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_services_role_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_services_role_proto = out.File
	file_schemas_greyseal_v1_services_role_proto_goTypes = nil
	file_schemas_greyseal_v1_services_role_proto_depIdxs = nil
}
