// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: ctx, system, prompt, emit
func (_m *MockGenerator) Generate(ctx context.Context, system string, prompt string, emit func(string) error) (string, error) {
	ret := _m.Called(ctx, system, prompt, emit)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, func(string) error) (string, error)); ok {
		return rf(ctx, system, prompt, emit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, func(string) error) string); ok {
		r0 = rf(ctx, system, prompt, emit)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, func(string) error) error); ok {
		r1 = rf(ctx, system, prompt, emit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
