// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	draft "github.com/holmes89/grey-seal/lib/greyseal/draft"
	mock "github.com/stretchr/testify/mock"
)

// MockDraftService is an autogenerated mock type for the DraftService type
type MockDraftService struct {
	mock.Mock
}

// Draft provides a mock function with given fields: ctx, req, emit
func (_m *MockDraftService) Draft(ctx context.Context, req draft.DraftRequest, emit func(string) error) (*draft.Result, error) {
	ret := _m.Called(ctx, req, emit)

	if len(ret) == 0 {
		panic("no return value specified for Draft")
	}

	var r0 *draft.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, draft.DraftRequest, func(string) error) (*draft.Result, error)); ok {
		return rf(ctx, req, emit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, draft.DraftRequest, func(string) error) *draft.Result); ok {
		r0 = rf(ctx, req, emit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*draft.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, draft.DraftRequest, func(string) error) error); ok {
		r1 = rf(ctx, req, emit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDraftService creates a new instance of MockDraftService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDraftService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDraftService {
	mock := &MockDraftService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
