// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/draft.proto

package servicesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DraftServiceName is the fully-qualified name of the DraftService service.
	DraftServiceName = "schemas.greyseal.services.v1.DraftService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DraftServiceDraftDocumentProcedure is the fully-qualified name of the DraftService's
	// DraftDocument RPC.
	DraftServiceDraftDocumentProcedure = "/schemas.greyseal.services.v1.DraftService/DraftDocument"
)

// DraftServiceClient is a client for the schemas.greyseal.services.v1.DraftService service.
type DraftServiceClient interface {
	// DraftDocument streams the draft's markdown as it is generated. The final
	// message has done=true and carries the full body, plus proposed specs
	// parsed from a design's "Domain objects" section.
	DraftDocument(context.Context, *connect.Request[services.DraftDocumentRequest]) (*connect.ServerStreamForClient[services.DraftDocumentChunk], error)
}

// NewDraftServiceClient constructs a client for the schemas.greyseal.services.v1.DraftService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDraftServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DraftServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	draftServiceMethods := services.File_schemas_greyseal_v1_services_draft_proto.Services().ByName("DraftService").Methods()
	return &draftServiceClient{
		draftDocument: connect.NewClient[services.DraftDocumentRequest, services.DraftDocumentChunk](
			httpClient,
			baseURL+DraftServiceDraftDocumentProcedure,
			connect.WithSchema(draftServiceMethods.ByName("DraftDocument")),
			connect.WithClientOptions(opts...),
		),
	}
}

// draftServiceClient implements DraftServiceClient.
type draftServiceClient struct {
	draftDocument *connect.Client[services.DraftDocumentRequest, services.DraftDocumentChunk]
}

// DraftDocument calls schemas.greyseal.services.v1.DraftService.DraftDocument.
func (c *draftServiceClient) DraftDocument(ctx context.Context, req *connect.Request[services.DraftDocumentRequest]) (*connect.ServerStreamForClient[services.DraftDocumentChunk], error) {
	return c.draftDocument.CallServerStream(ctx, req)
}

// DraftServiceHandler is an implementation of the schemas.greyseal.services.v1.DraftService
// service.
type DraftServiceHandler interface {
	// DraftDocument streams the draft's markdown as it is generated. The final
	// message has done=true and carries the full body, plus proposed specs
	// parsed from a design's "Domain objects" section.
	DraftDocument(context.Context, *connect.Request[services.DraftDocumentRequest], *connect.ServerStream[services.DraftDocumentChunk]) error
}

// NewDraftServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDraftServiceHandler(svc DraftServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	draftServiceMethods := services.File_schemas_greyseal_v1_services_draft_proto.Services().ByName("DraftService").Methods()
	draftServiceDraftDocumentHandler := connect.NewServerStreamHandler(
		DraftServiceDraftDocumentProcedure,
		svc.DraftDocument,
		connect.WithSchema(draftServiceMethods.ByName("DraftDocument")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.services.v1.DraftService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DraftServiceDraftDocumentProcedure:
			draftServiceDraftDocumentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDraftServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDraftServiceHandler struct{}

func (UnimplementedDraftServiceHandler) DraftDocument(context.Context, *connect.Request[services.DraftDocumentRequest], *connect.ServerStream[services.DraftDocumentChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.DraftService.DraftDocument is not implemented"))
}
