// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/question.proto

package servicesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QuestionServiceName is the fully-qualified name of the QuestionService service.
	QuestionServiceName = "schemas.greyseal.v1.services.v1.QuestionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QuestionServiceListQuestionsProcedure is the fully-qualified name of the QuestionService's
	// ListQuestions RPC.
	QuestionServiceListQuestionsProcedure = "/schemas.greyseal.v1.services.v1.QuestionService/ListQuestions"
	// QuestionServiceGetQuestionProcedure is the fully-qualified name of the QuestionService's
	// GetQuestion RPC.
	QuestionServiceGetQuestionProcedure = "/schemas.greyseal.v1.services.v1.QuestionService/GetQuestion"
	// QuestionServiceCreateQuestionProcedure is the fully-qualified name of the QuestionService's
	// CreateQuestion RPC.
	QuestionServiceCreateQuestionProcedure = "/schemas.greyseal.v1.services.v1.QuestionService/CreateQuestion"
)

// QuestionServiceClient is a client for the schemas.greyseal.v1.services.v1.QuestionService
// service.
type QuestionServiceClient interface {
	ListQuestions(context.Context, *connect.Request[services.ListQuestionsRequest]) (*connect.Response[services.ListQuestionsResponse], error)
	GetQuestion(context.Context, *connect.Request[services.GetQuestionRequest]) (*connect.Response[services.GetQuestionResponse], error)
	CreateQuestion(context.Context, *connect.Request[services.CreateQuestionRequest]) (*connect.Response[services.CreateQuestionResponse], error)
}

// NewQuestionServiceClient constructs a client for the
// schemas.greyseal.v1.services.v1.QuestionService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQuestionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QuestionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	questionServiceMethods := services.File_schemas_greyseal_v1_services_question_proto.Services().ByName("QuestionService").Methods()
	return &questionServiceClient{
		listQuestions: connect.NewClient[services.ListQuestionsRequest, services.ListQuestionsResponse](
			httpClient,
			baseURL+QuestionServiceListQuestionsProcedure,
			connect.WithSchema(questionServiceMethods.ByName("ListQuestions")),
			connect.WithClientOptions(opts...),
		),
		getQuestion: connect.NewClient[services.GetQuestionRequest, services.GetQuestionResponse](
			httpClient,
			baseURL+QuestionServiceGetQuestionProcedure,
			connect.WithSchema(questionServiceMethods.ByName("GetQuestion")),
			connect.WithClientOptions(opts...),
		),
		createQuestion: connect.NewClient[services.CreateQuestionRequest, services.CreateQuestionResponse](
			httpClient,
			baseURL+QuestionServiceCreateQuestionProcedure,
			connect.WithSchema(questionServiceMethods.ByName("CreateQuestion")),
			connect.WithClientOptions(opts...),
		),
	}
}

// questionServiceClient implements QuestionServiceClient.
type questionServiceClient struct {
	listQuestions  *connect.Client[services.ListQuestionsRequest, services.ListQuestionsResponse]
	getQuestion    *connect.Client[services.GetQuestionRequest, services.GetQuestionResponse]
	createQuestion *connect.Client[services.CreateQuestionRequest, services.CreateQuestionResponse]
}

// ListQuestions calls schemas.greyseal.v1.services.v1.QuestionService.ListQuestions.
func (c *questionServiceClient) ListQuestions(ctx context.Context, req *connect.Request[services.ListQuestionsRequest]) (*connect.Response[services.ListQuestionsResponse], error) {
	return c.listQuestions.CallUnary(ctx, req)
}

// GetQuestion calls schemas.greyseal.v1.services.v1.QuestionService.GetQuestion.
func (c *questionServiceClient) GetQuestion(ctx context.Context, req *connect.Request[services.GetQuestionRequest]) (*connect.Response[services.GetQuestionResponse], error) {
	return c.getQuestion.CallUnary(ctx, req)
}

// CreateQuestion calls schemas.greyseal.v1.services.v1.QuestionService.CreateQuestion.
func (c *questionServiceClient) CreateQuestion(ctx context.Context, req *connect.Request[services.CreateQuestionRequest]) (*connect.Response[services.CreateQuestionResponse], error) {
	return c.createQuestion.CallUnary(ctx, req)
}

// QuestionServiceHandler is an implementation of the
// schemas.greyseal.v1.services.v1.QuestionService service.
type QuestionServiceHandler interface {
	ListQuestions(context.Context, *connect.Request[services.ListQuestionsRequest]) (*connect.Response[services.ListQuestionsResponse], error)
	GetQuestion(context.Context, *connect.Request[services.GetQuestionRequest]) (*connect.Response[services.GetQuestionResponse], error)
	CreateQuestion(context.Context, *connect.Request[services.CreateQuestionRequest]) (*connect.Response[services.CreateQuestionResponse], error)
}

// NewQuestionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQuestionServiceHandler(svc QuestionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	questionServiceMethods := services.File_schemas_greyseal_v1_services_question_proto.Services().ByName("QuestionService").Methods()
	questionServiceListQuestionsHandler := connect.NewUnaryHandler(
		QuestionServiceListQuestionsProcedure,
		svc.ListQuestions,
		connect.WithSchema(questionServiceMethods.ByName("ListQuestions")),
		connect.WithHandlerOptions(opts...),
	)
	questionServiceGetQuestionHandler := connect.NewUnaryHandler(
		QuestionServiceGetQuestionProcedure,
		svc.GetQuestion,
		connect.WithSchema(questionServiceMethods.ByName("GetQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	questionServiceCreateQuestionHandler := connect.NewUnaryHandler(
		QuestionServiceCreateQuestionProcedure,
		svc.CreateQuestion,
		connect.WithSchema(questionServiceMethods.ByName("CreateQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.v1.services.v1.QuestionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QuestionServiceListQuestionsProcedure:
			questionServiceListQuestionsHandler.ServeHTTP(w, r)
		case QuestionServiceGetQuestionProcedure:
			questionServiceGetQuestionHandler.ServeHTTP(w, r)
		case QuestionServiceCreateQuestionProcedure:
			questionServiceCreateQuestionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQuestionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQuestionServiceHandler struct{}

func (UnimplementedQuestionServiceHandler) ListQuestions(context.Context, *connect.Request[services.ListQuestionsRequest]) (*connect.Response[services.ListQuestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.v1.services.v1.QuestionService.ListQuestions is not implemented"))
}

func (UnimplementedQuestionServiceHandler) GetQuestion(context.Context, *connect.Request[services.GetQuestionRequest]) (*connect.Response[services.GetQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.v1.services.v1.QuestionService.GetQuestion is not implemented"))
}

func (UnimplementedQuestionServiceHandler) CreateQuestion(context.Context, *connect.Request[services.CreateQuestionRequest]) (*connect.Response[services.CreateQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.v1.services.v1.QuestionService.CreateQuestion is not implemented"))
}
