// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/resource.proto

package servicesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResourceServiceName is the fully-qualified name of the ResourceService service.
	ResourceServiceName = "schemas.greyseal.services.v1.ResourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourceServiceIngestResourceProcedure is the fully-qualified name of the ResourceService's
	// IngestResource RPC.
	ResourceServiceIngestResourceProcedure = "/schemas.greyseal.services.v1.ResourceService/IngestResource"
	// ResourceServiceGetResourceProcedure is the fully-qualified name of the ResourceService's
	// GetResource RPC.
	ResourceServiceGetResourceProcedure = "/schemas.greyseal.services.v1.ResourceService/GetResource"
	// ResourceServiceListResourcesProcedure is the fully-qualified name of the ResourceService's
	// ListResources RPC.
	ResourceServiceListResourcesProcedure = "/schemas.greyseal.services.v1.ResourceService/ListResources"
	// ResourceServiceDeleteResourceProcedure is the fully-qualified name of the ResourceService's
	// DeleteResource RPC.
	ResourceServiceDeleteResourceProcedure = "/schemas.greyseal.services.v1.ResourceService/DeleteResource"
)

// ResourceServiceClient is a client for the schemas.greyseal.services.v1.ResourceService service.
type ResourceServiceClient interface {
	// IngestResource ingests a magpie resource, chunks it, and stores embeddings.
	IngestResource(context.Context, *connect.Request[services.IngestResourceRequest]) (*connect.Response[services.IngestResourceResponse], error)
	GetResource(context.Context, *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error)
	ListResources(context.Context, *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error)
	DeleteResource(context.Context, *connect.Request[services.DeleteResourceRequest]) (*connect.Response[services.DeleteResourceResponse], error)
}

// NewResourceServiceClient constructs a client for the schemas.greyseal.services.v1.ResourceService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resourceServiceMethods := services.File_schemas_greyseal_v1_services_resource_proto.Services().ByName("ResourceService").Methods()
	return &resourceServiceClient{
		ingestResource: connect.NewClient[services.IngestResourceRequest, services.IngestResourceResponse](
			httpClient,
			baseURL+ResourceServiceIngestResourceProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("IngestResource")),
			connect.WithClientOptions(opts...),
		),
		getResource: connect.NewClient[services.GetResourceRequest, services.GetResourceResponse](
			httpClient,
			baseURL+ResourceServiceGetResourceProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("GetResource")),
			connect.WithClientOptions(opts...),
		),
		listResources: connect.NewClient[services.ListResourcesRequest, services.ListResourcesResponse](
			httpClient,
			baseURL+ResourceServiceListResourcesProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("ListResources")),
			connect.WithClientOptions(opts...),
		),
		deleteResource: connect.NewClient[services.DeleteResourceRequest, services.DeleteResourceResponse](
			httpClient,
			baseURL+ResourceServiceDeleteResourceProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("DeleteResource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resourceServiceClient implements ResourceServiceClient.
type resourceServiceClient struct {
	ingestResource *connect.Client[services.IngestResourceRequest, services.IngestResourceResponse]
	getResource    *connect.Client[services.GetResourceRequest, services.GetResourceResponse]
	listResources  *connect.Client[services.ListResourcesRequest, services.ListResourcesResponse]
	deleteResource *connect.Client[services.DeleteResourceRequest, services.DeleteResourceResponse]
}

// IngestResource calls schemas.greyseal.services.v1.ResourceService.IngestResource.
func (c *resourceServiceClient) IngestResource(ctx context.Context, req *connect.Request[services.IngestResourceRequest]) (*connect.Response[services.IngestResourceResponse], error) {
	return c.ingestResource.CallUnary(ctx, req)
}

// GetResource calls schemas.greyseal.services.v1.ResourceService.GetResource.
func (c *resourceServiceClient) GetResource(ctx context.Context, req *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error) {
	return c.getResource.CallUnary(ctx, req)
}

// ListResources calls schemas.greyseal.services.v1.ResourceService.ListResources.
func (c *resourceServiceClient) ListResources(ctx context.Context, req *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error) {
	return c.listResources.CallUnary(ctx, req)
}

// DeleteResource calls schemas.greyseal.services.v1.ResourceService.DeleteResource.
func (c *resourceServiceClient) DeleteResource(ctx context.Context, req *connect.Request[services.DeleteResourceRequest]) (*connect.Response[services.DeleteResourceResponse], error) {
	return c.deleteResource.CallUnary(ctx, req)
}

// ResourceServiceHandler is an implementation of the schemas.greyseal.services.v1.ResourceService
// service.
type ResourceServiceHandler interface {
	// IngestResource ingests a magpie resource, chunks it, and stores embeddings.
	IngestResource(context.Context, *connect.Request[services.IngestResourceRequest]) (*connect.Response[services.IngestResourceResponse], error)
	GetResource(context.Context, *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error)
	ListResources(context.Context, *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error)
	DeleteResource(context.Context, *connect.Request[services.DeleteResourceRequest]) (*connect.Response[services.DeleteResourceResponse], error)
}

// NewResourceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResourceServiceHandler(svc ResourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resourceServiceMethods := services.File_schemas_greyseal_v1_services_resource_proto.Services().ByName("ResourceService").Methods()
	resourceServiceIngestResourceHandler := connect.NewUnaryHandler(
		ResourceServiceIngestResourceProcedure,
		svc.IngestResource,
		connect.WithSchema(resourceServiceMethods.ByName("IngestResource")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceGetResourceHandler := connect.NewUnaryHandler(
		ResourceServiceGetResourceProcedure,
		svc.GetResource,
		connect.WithSchema(resourceServiceMethods.ByName("GetResource")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceListResourcesHandler := connect.NewUnaryHandler(
		ResourceServiceListResourcesProcedure,
		svc.ListResources,
		connect.WithSchema(resourceServiceMethods.ByName("ListResources")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceDeleteResourceHandler := connect.NewUnaryHandler(
		ResourceServiceDeleteResourceProcedure,
		svc.DeleteResource,
		connect.WithSchema(resourceServiceMethods.ByName("DeleteResource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.services.v1.ResourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResourceServiceIngestResourceProcedure:
			resourceServiceIngestResourceHandler.ServeHTTP(w, r)
		case ResourceServiceGetResourceProcedure:
			resourceServiceGetResourceHandler.ServeHTTP(w, r)
		case ResourceServiceListResourcesProcedure:
			resourceServiceListResourcesHandler.ServeHTTP(w, r)
		case ResourceServiceDeleteResourceProcedure:
			resourceServiceDeleteResourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResourceServiceHandler struct{}

func (UnimplementedResourceServiceHandler) IngestResource(context.Context, *connect.Request[services.IngestResourceRequest]) (*connect.Response[services.IngestResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ResourceService.IngestResource is not implemented"))
}

func (UnimplementedResourceServiceHandler) GetResource(context.Context, *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ResourceService.GetResource is not implemented"))
}

func (UnimplementedResourceServiceHandler) ListResources(context.Context, *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ResourceService.ListResources is not implemented"))
}

func (UnimplementedResourceServiceHandler) DeleteResource(context.Context, *connect.Request[services.DeleteResourceRequest]) (*connect.Response[services.DeleteResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.services.v1.ResourceService.DeleteResource is not implemented"))
}
