// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: schemas/greyseal/v1/services/resource.proto

package servicesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResourceServiceName is the fully-qualified name of the ResourceService service.
	ResourceServiceName = "schemas.greyseal.v1.services.v1.ResourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourceServiceListResourcesProcedure is the fully-qualified name of the ResourceService's
	// ListResources RPC.
	ResourceServiceListResourcesProcedure = "/schemas.greyseal.v1.services.v1.ResourceService/ListResources"
	// ResourceServiceGetResourceProcedure is the fully-qualified name of the ResourceService's
	// GetResource RPC.
	ResourceServiceGetResourceProcedure = "/schemas.greyseal.v1.services.v1.ResourceService/GetResource"
	// ResourceServiceCreateResourceProcedure is the fully-qualified name of the ResourceService's
	// CreateResource RPC.
	ResourceServiceCreateResourceProcedure = "/schemas.greyseal.v1.services.v1.ResourceService/CreateResource"
)

// ResourceServiceClient is a client for the schemas.greyseal.v1.services.v1.ResourceService
// service.
type ResourceServiceClient interface {
	ListResources(context.Context, *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error)
	GetResource(context.Context, *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error)
	CreateResource(context.Context, *connect.Request[services.CreateResourceRequest]) (*connect.Response[services.CreateResourceResponse], error)
}

// NewResourceServiceClient constructs a client for the
// schemas.greyseal.v1.services.v1.ResourceService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resourceServiceMethods := services.File_schemas_greyseal_v1_services_resource_proto.Services().ByName("ResourceService").Methods()
	return &resourceServiceClient{
		listResources: connect.NewClient[services.ListResourcesRequest, services.ListResourcesResponse](
			httpClient,
			baseURL+ResourceServiceListResourcesProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("ListResources")),
			connect.WithClientOptions(opts...),
		),
		getResource: connect.NewClient[services.GetResourceRequest, services.GetResourceResponse](
			httpClient,
			baseURL+ResourceServiceGetResourceProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("GetResource")),
			connect.WithClientOptions(opts...),
		),
		createResource: connect.NewClient[services.CreateResourceRequest, services.CreateResourceResponse](
			httpClient,
			baseURL+ResourceServiceCreateResourceProcedure,
			connect.WithSchema(resourceServiceMethods.ByName("CreateResource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resourceServiceClient implements ResourceServiceClient.
type resourceServiceClient struct {
	listResources  *connect.Client[services.ListResourcesRequest, services.ListResourcesResponse]
	getResource    *connect.Client[services.GetResourceRequest, services.GetResourceResponse]
	createResource *connect.Client[services.CreateResourceRequest, services.CreateResourceResponse]
}

// ListResources calls schemas.greyseal.v1.services.v1.ResourceService.ListResources.
func (c *resourceServiceClient) ListResources(ctx context.Context, req *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error) {
	return c.listResources.CallUnary(ctx, req)
}

// GetResource calls schemas.greyseal.v1.services.v1.ResourceService.GetResource.
func (c *resourceServiceClient) GetResource(ctx context.Context, req *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error) {
	return c.getResource.CallUnary(ctx, req)
}

// CreateResource calls schemas.greyseal.v1.services.v1.ResourceService.CreateResource.
func (c *resourceServiceClient) CreateResource(ctx context.Context, req *connect.Request[services.CreateResourceRequest]) (*connect.Response[services.CreateResourceResponse], error) {
	return c.createResource.CallUnary(ctx, req)
}

// ResourceServiceHandler is an implementation of the
// schemas.greyseal.v1.services.v1.ResourceService service.
type ResourceServiceHandler interface {
	ListResources(context.Context, *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error)
	GetResource(context.Context, *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error)
	CreateResource(context.Context, *connect.Request[services.CreateResourceRequest]) (*connect.Response[services.CreateResourceResponse], error)
}

// NewResourceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResourceServiceHandler(svc ResourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resourceServiceMethods := services.File_schemas_greyseal_v1_services_resource_proto.Services().ByName("ResourceService").Methods()
	resourceServiceListResourcesHandler := connect.NewUnaryHandler(
		ResourceServiceListResourcesProcedure,
		svc.ListResources,
		connect.WithSchema(resourceServiceMethods.ByName("ListResources")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceGetResourceHandler := connect.NewUnaryHandler(
		ResourceServiceGetResourceProcedure,
		svc.GetResource,
		connect.WithSchema(resourceServiceMethods.ByName("GetResource")),
		connect.WithHandlerOptions(opts...),
	)
	resourceServiceCreateResourceHandler := connect.NewUnaryHandler(
		ResourceServiceCreateResourceProcedure,
		svc.CreateResource,
		connect.WithSchema(resourceServiceMethods.ByName("CreateResource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/schemas.greyseal.v1.services.v1.ResourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResourceServiceListResourcesProcedure:
			resourceServiceListResourcesHandler.ServeHTTP(w, r)
		case ResourceServiceGetResourceProcedure:
			resourceServiceGetResourceHandler.ServeHTTP(w, r)
		case ResourceServiceCreateResourceProcedure:
			resourceServiceCreateResourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResourceServiceHandler struct{}

func (UnimplementedResourceServiceHandler) ListResources(context.Context, *connect.Request[services.ListResourcesRequest]) (*connect.Response[services.ListResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.v1.services.v1.ResourceService.ListResources is not implemented"))
}

func (UnimplementedResourceServiceHandler) GetResource(context.Context, *connect.Request[services.GetResourceRequest]) (*connect.Response[services.GetResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.v1.services.v1.ResourceService.GetResource is not implemented"))
}

func (UnimplementedResourceServiceHandler) CreateResource(context.Context, *connect.Request[services.CreateResourceRequest]) (*connect.Response[services.CreateResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("schemas.greyseal.v1.services.v1.ResourceService.CreateResource is not implemented"))
}
