// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockRoleRepository is a mock type for the base.Repository[*Role] interface.
type MockRoleRepository struct {
	mock.Mock
}

func (_m *MockRoleRepository) Create(ctx context.Context, entity *v1.Role) error {
	ret := _m.Called(ctx, entity)
	return ret.Error(0)
}

func (_m *MockRoleRepository) Update(ctx context.Context, id string, entity *v1.Role) error {
	ret := _m.Called(ctx, id, entity)
	return ret.Error(0)
}

func (_m *MockRoleRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func (_m *MockRoleRepository) Get(ctx context.Context, id string) (*v1.Role, error) {
	ret := _m.Called(ctx, id)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Role), ret.Error(1)
}

func (_m *MockRoleRepository) List(ctx context.Context, cursor string, limit uint, filter map[string][]any) ([]*v1.Role, error) {
	ret := _m.Called(ctx, cursor, limit, filter)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]*v1.Role), ret.Error(1)
}

func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	m := &MockRoleRepository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
