// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /home/joel/projects/grey-seal && make generate

package mocks

import (
	"context"

	"github.com/holmes89/archaea/base"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockRoleService is a mock type for the RoleService interface.
type MockRoleService struct {
	mock.Mock
}

func (_m *MockRoleService) List(ctx context.Context, req base.ListRequest) (base.ListResponse[*v1.Role], error) {
	ret := _m.Called(ctx, req)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.ListResponse[*v1.Role]), ret.Error(1)
}

func (_m *MockRoleService) Get(ctx context.Context, req base.GetRequest[*v1.Role]) (base.GetResponse[*v1.Role], error) {
	ret := _m.Called(ctx, req)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.GetResponse[*v1.Role]), ret.Error(1)
}

func (_m *MockRoleService) Create(ctx context.Context, req base.CreateRequest[*v1.Role]) (base.CreateResponse[*v1.Role], error) {
	ret := _m.Called(ctx, req)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.CreateResponse[*v1.Role]), ret.Error(1)
}

func (_m *MockRoleService) Update(ctx context.Context, id string, data *v1.Role) (*v1.Role, error) {
	ret := _m.Called(ctx, id, data)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Role), ret.Error(1)
}

func (_m *MockRoleService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	m := &MockRoleService{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
