// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /Users/joel/dev/grey-seal && make generate

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockIndexer is a mock type for the Indexer interface.
type MockIndexer struct {
	mock.Mock
}

func (_m *MockIndexer) Index(ctx context.Context, resource *v1.Resource) error {
	ret := _m.Called(ctx, resource)
	return ret.Error(0)
}

func NewMockIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexer {
	m := &MockIndexer{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
