// Code generated by mockery v2. DO NOT EDIT.
// Regenerate: cd /Users/joel/dev/grey-seal && make generate

package mocks

import (
	"context"

	"github.com/holmes89/archaea/base"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/holmes89/grey-seal/lib/schemas/greyseal/v1"
)

// MockResourceService is a mock type for the ResourceService interface.
type MockResourceService struct {
	mock.Mock
}

func (_m *MockResourceService) List(ctx context.Context, lis base.ListRequest) (base.ListResponse[*v1.Resource], error) {
	ret := _m.Called(ctx, lis)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.ListResponse[*v1.Resource]), ret.Error(1)
}

func (_m *MockResourceService) Get(ctx context.Context, get base.GetRequest[*v1.Resource]) (base.GetResponse[*v1.Resource], error) {
	ret := _m.Called(ctx, get)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(base.GetResponse[*v1.Resource]), ret.Error(1)
}

func (_m *MockResourceService) Ingest(ctx context.Context, data *v1.Resource) (*v1.Resource, error) {
	ret := _m.Called(ctx, data)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*v1.Resource), ret.Error(1)
}

func (_m *MockResourceService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func NewMockResourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceService {
	m := &MockResourceService{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
