// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: schemas/greyseal/v1/agent.proto

package greysealv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentRun is the persisted state of one agentic coding-task run.
type AgentRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// provider: "claude" (Managed Agents) — the only implemented value in
	// Phase 1. "ollama:<model>" is a reserved, not-yet-implemented value.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	RepoUrl  string `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// status: "running" | "idle" | "terminated" | "error".
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// session_id is the provider's session identifier — for Claude this is a
	// Managed Agents session ID, usable to build a Console trace-view link.
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// pr_url is populated once the agent opens a pull request, if it does.
	PrUrl string `protobuf:"bytes,6,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	// error holds a human-readable failure reason when status is "error".
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRun) Reset() {
	*x = AgentRun{}
	mi := &file_schemas_greyseal_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRun) ProtoMessage() {}

func (x *AgentRun) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRun.ProtoReflect.Descriptor instead.
func (*AgentRun) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRun) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AgentRun) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentRun) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *AgentRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRun) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentRun) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *AgentRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentRun) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_schemas_greyseal_v1_agent_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1fschemas/greyseal/v1/agent.proto\x12\x13schemas.greyseal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n" +
	"\bAgentRun\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\brepo_url\x18\x03 \x01(\tR\arepoUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06pr_url\x18\x06 \x01(\tR\x05prUrl\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\xd5\x01\n" +
	"\x17com.schemas.greyseal.v1B\n" +
	"AgentProtoP\x01Z@github.com/holmes89/grey-seal/lib/schemas/greyseal/v1;greysealv1\xa2\x02\x03SGX\xaa\x02\x13Schemas.Greyseal.V1\xca\x02\x13Schemas\\Greyseal\\V1\xe2\x02\x1fSchemas\\Greyseal\\V1\\GPBMetadata\xea\x02\x15Schemas::Greyseal::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_agent_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_agent_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_agent_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_agent_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_agent_proto_rawDesc), len(file_schemas_greyseal_v1_agent_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_agent_proto_rawDescData
}

var file_schemas_greyseal_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schemas_greyseal_v1_agent_proto_goTypes = []any{
	(*AgentRun)(nil),              // 0: schemas.greyseal.v1.AgentRun
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_schemas_greyseal_v1_agent_proto_depIdxs = []int32{
	1, // 0: schemas.greyseal.v1.AgentRun.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: schemas.greyseal.v1.AgentRun.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_agent_proto_init() }
func file_schemas_greyseal_v1_agent_proto_init() {
	if File_schemas_greyseal_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_agent_proto_rawDesc), len(file_schemas_greyseal_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_greyseal_v1_agent_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_agent_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_agent_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_agent_proto = out.File
	file_schemas_greyseal_v1_agent_proto_goTypes = nil
	file_schemas_greyseal_v1_agent_proto_depIdxs = nil
}
