// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schemas/greyseal/v1/conversation.proto

package greysealv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 1
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 2
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_USER",
		2: "MESSAGE_ROLE_ASSISTANT",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_USER":        1,
		"MESSAGE_ROLE_ASSISTANT":   2,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_schemas_greyseal_v1_conversation_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_schemas_greyseal_v1_conversation_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_conversation_proto_rawDescGZIP(), []int{0}
}

// Message is a single turn in a conversation.
type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ConversationUuid string                 `protobuf:"bytes,2,opt,name=conversation_uuid,json=conversationUuid,proto3" json:"conversation_uuid,omitempty"`
	Role             MessageRole            `protobuf:"varint,3,opt,name=role,proto3,enum=schemas.greyseal.v1.MessageRole" json:"role,omitempty"`
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// resource_uuids holds references to indexed resources used to generate
	// this response (populated for ASSISTANT messages).
	ResourceUuids []string `protobuf:"bytes,5,rep,name=resource_uuids,json=resourceUuids,proto3" json:"resource_uuids,omitempty"`
	// feedback allows simple quality tracking: -1 negative, 0 neutral, 1 positive.
	Feedback      int32                  `protobuf:"varint,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_schemas_greyseal_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetConversationUuid() string {
	if x != nil {
		return x.ConversationUuid
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetResourceUuids() []string {
	if x != nil {
		return x.ResourceUuids
	}
	return nil
}

func (x *Message) GetFeedback() int32 {
	if x != nil {
		return x.Feedback
	}
	return 0
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Conversation is a chat session that persists and can be resumed.
type Conversation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// title is an optional display name; can be set manually or auto-generated
	// from the first exchange.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// role_uuid optionally links to a Role that sets the system prompt.
	RoleUuid string `protobuf:"bytes,3,opt,name=role_uuid,json=roleUuid,proto3" json:"role_uuid,omitempty"`
	// resource_uuids optionally scopes retrieval to a specific set of resources.
	// When empty, all indexed resources are searched.
	ResourceUuids []string `protobuf:"bytes,4,rep,name=resource_uuids,json=resourceUuids,proto3" json:"resource_uuids,omitempty"`
	// summary holds a rolling compressed summary of older messages to manage
	// context window length.
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Messages      []*Message             `protobuf:"bytes,6,rep,name=messages,proto3" json:"messages,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_schemas_greyseal_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetRoleUuid() string {
	if x != nil {
		return x.RoleUuid
	}
	return ""
}

func (x *Conversation) GetResourceUuids() []string {
	if x != nil {
		return x.ResourceUuids
	}
	return nil
}

func (x *Conversation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Conversation) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_schemas_greyseal_v1_conversation_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"&schemas/greyseal/v1/conversation.proto\x12\x13schemas.greyseal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12+\n" +
	"\x11conversation_uuid\x18\x02 \x01(\tR\x10conversationUuid\x124\n" +
	"\x04role\x18\x03 \x01(\x0e2 .schemas.greyseal.v1.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12%\n" +
	"\x0eresource_uuids\x18\x05 \x03(\tR\rresourceUuids\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\x05R\bfeedback\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc6\x02\n" +
	"\fConversation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\trole_uuid\x18\x03 \x01(\tR\broleUuid\x12%\n" +
	"\x0eresource_uuids\x18\x04 \x03(\tR\rresourceUuids\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x128\n" +
	"\bmessages\x18\x06 \x03(\v2\x1c.schemas.greyseal.v1.MessageR\bmessages\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*^\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x02B\xdc\x01\n" +
	"\x17com.schemas.greyseal.v1B\x11ConversationProtoP\x01Z@github.com/holmes89/grey-seal/lib/schemas/greyseal/v1;greysealv1\xa2\x02\x03SGX\xaa\x02\x13Schemas.Greyseal.V1\xca\x02\x13Schemas\\Greyseal\\V1\xe2\x02\x1fSchemas\\Greyseal\\V1\\GPBMetadata\xea\x02\x15Schemas::Greyseal::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_conversation_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_conversation_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_conversation_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_conversation_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_conversation_proto_rawDesc), len(file_schemas_greyseal_v1_conversation_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_conversation_proto_rawDescData
}

var file_schemas_greyseal_v1_conversation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemas_greyseal_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schemas_greyseal_v1_conversation_proto_goTypes = []any{
	(MessageRole)(0),              // 0: schemas.greyseal.v1.MessageRole
	(*Message)(nil),               // 1: schemas.greyseal.v1.Message
	(*Conversation)(nil),          // 2: schemas.greyseal.v1.Conversation
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_schemas_greyseal_v1_conversation_proto_depIdxs = []int32{
	0, // 0: schemas.greyseal.v1.Message.role:type_name -> schemas.greyseal.v1.MessageRole
	3, // 1: schemas.greyseal.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: schemas.greyseal.v1.Conversation.messages:type_name -> schemas.greyseal.v1.Message
	3, // 3: schemas.greyseal.v1.Conversation.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: schemas.greyseal.v1.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_conversation_proto_init() }
func file_schemas_greyseal_v1_conversation_proto_init() {
	if File_schemas_greyseal_v1_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_conversation_proto_rawDesc), len(file_schemas_greyseal_v1_conversation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_greyseal_v1_conversation_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_conversation_proto_depIdxs,
		EnumInfos:         file_schemas_greyseal_v1_conversation_proto_enumTypes,
		MessageInfos:      file_schemas_greyseal_v1_conversation_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_conversation_proto = out.File
	file_schemas_greyseal_v1_conversation_proto_goTypes = nil
	file_schemas_greyseal_v1_conversation_proto_depIdxs = nil
}
