// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: schemas/greyseal/v1/question.proto

package greysealv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	RoleDescription string                 `protobuf:"bytes,2,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_schemas_greyseal_v1_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_question_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Question) GetRoleDescription() string {
	if x != nil {
		return x.RoleDescription
	}
	return ""
}

func (x *Question) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	References    []string               `protobuf:"bytes,3,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_schemas_greyseal_v1_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_question_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Answer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Answer) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

var File_schemas_greyseal_v1_question_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_question_proto_rawDesc = "" +
	"\n" +
	"\"schemas/greyseal/v1/question.proto\x12\x13schemas.greyseal.v1\"c\n" +
	"\bQuestion\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12)\n" +
	"\x10role_description\x18\x02 \x01(\tR\x0froleDescription\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"V\n" +
	"\x06Answer\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"references\x18\x03 \x03(\tR\n" +
	"referencesB\xd8\x01\n" +
	"\x17com.schemas.greyseal.v1B\rQuestionProtoP\x01Z@github.com/holmes89/grey-seal/lib/schemas/greyseal/v1;greysealv1\xa2\x02\x03SGX\xaa\x02\x13Schemas.Greyseal.V1\xca\x02\x13Schemas\\Greyseal\\V1\xe2\x02\x1fSchemas\\Greyseal\\V1\\GPBMetadata\xea\x02\x15Schemas::Greyseal::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_question_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_question_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_question_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_question_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_question_proto_rawDesc), len(file_schemas_greyseal_v1_question_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_question_proto_rawDescData
}

var file_schemas_greyseal_v1_question_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schemas_greyseal_v1_question_proto_goTypes = []any{
	(*Question)(nil), // 0: schemas.greyseal.v1.Question
	(*Answer)(nil),   // 1: schemas.greyseal.v1.Answer
}
var file_schemas_greyseal_v1_question_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_question_proto_init() }
func file_schemas_greyseal_v1_question_proto_init() {
	if File_schemas_greyseal_v1_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_question_proto_rawDesc), len(file_schemas_greyseal_v1_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_greyseal_v1_question_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_question_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_question_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_question_proto = out.File
	file_schemas_greyseal_v1_question_proto_goTypes = nil
	file_schemas_greyseal_v1_question_proto_depIdxs = nil
}
