// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schemas/greyseal/v1/resource.proto

package greysealv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Source int32

const (
	Source_SOURCE_UNSPECIFIED Source = 0
	Source_SOURCE_WEBSITE     Source = 1
	Source_SOURCE_PDF         Source = 2
	Source_SOURCE_TEXT        Source = 3
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_WEBSITE",
		2: "SOURCE_PDF",
		3: "SOURCE_TEXT",
	}
	Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"SOURCE_WEBSITE":     1,
		"SOURCE_PDF":         2,
		"SOURCE_TEXT":        3,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_schemas_greyseal_v1_resource_proto_enumTypes[0].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_schemas_greyseal_v1_resource_proto_enumTypes[0]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_resource_proto_rawDescGZIP(), []int{0}
}

// Resource represents an ingested and indexed document used as conversation context.
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Entity        string                 `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity,omitempty"`
	Source        Source                 `protobuf:"varint,5,opt,name=source,proto3,enum=schemas.greyseal.v1.Source" json:"source,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_schemas_greyseal_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Resource) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Resource) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (x *Resource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

var File_schemas_greyseal_v1_resource_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\"schemas/greyseal/v1/resource.proto\x12\x13schemas.greyseal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\bResource\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06entity\x18\x04 \x01(\tR\x06entity\x123\n" +
	"\x06source\x18\x05 \x01(\x0e2\x1b.schemas.greyseal.v1.SourceR\x06source\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"indexed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt*U\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSOURCE_WEBSITE\x10\x01\x12\x0e\n" +
	"\n" +
	"SOURCE_PDF\x10\x02\x12\x0f\n" +
	"\vSOURCE_TEXT\x10\x03B\xd8\x01\n" +
	"\x17com.schemas.greyseal.v1B\rResourceProtoP\x01Z@github.com/holmes89/grey-seal/lib/schemas/greyseal/v1;greysealv1\xa2\x02\x03SGX\xaa\x02\x13Schemas.Greyseal.V1\xca\x02\x13Schemas\\Greyseal\\V1\xe2\x02\x1fSchemas\\Greyseal\\V1\\GPBMetadata\xea\x02\x15Schemas::Greyseal::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_resource_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_resource_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_resource_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_resource_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_resource_proto_rawDesc), len(file_schemas_greyseal_v1_resource_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_resource_proto_rawDescData
}

var file_schemas_greyseal_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemas_greyseal_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schemas_greyseal_v1_resource_proto_goTypes = []any{
	(Source)(0),                   // 0: schemas.greyseal.v1.Source
	(*Resource)(nil),              // 1: schemas.greyseal.v1.Resource
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_schemas_greyseal_v1_resource_proto_depIdxs = []int32{
	0, // 0: schemas.greyseal.v1.Resource.source:type_name -> schemas.greyseal.v1.Source
	2, // 1: schemas.greyseal.v1.Resource.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: schemas.greyseal.v1.Resource.indexed_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_resource_proto_init() }
func file_schemas_greyseal_v1_resource_proto_init() {
	if File_schemas_greyseal_v1_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_resource_proto_rawDesc), len(file_schemas_greyseal_v1_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_greyseal_v1_resource_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_resource_proto_depIdxs,
		EnumInfos:         file_schemas_greyseal_v1_resource_proto_enumTypes,
		MessageInfos:      file_schemas_greyseal_v1_resource_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_resource_proto = out.File
	file_schemas_greyseal_v1_resource_proto_goTypes = nil
	file_schemas_greyseal_v1_resource_proto_depIdxs = nil
}
