// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: schemas/greyseal/v1/role.proto

package greysealv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is a reusable named system prompt that can be assigned to a conversation
// to shape how the chatbot responds. Leaving role_uuid blank on a conversation
// means no system prompt is applied.
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_schemas_greyseal_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_greyseal_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_schemas_greyseal_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_schemas_greyseal_v1_role_proto protoreflect.FileDescriptor

const file_schemas_greyseal_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x1eschemas/greyseal/v1/role.proto\x12\x13schemas.greyseal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x04Role\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\xd4\x01\n" +
	"\x17com.schemas.greyseal.v1B\tRoleProtoP\x01Z@github.com/holmes89/grey-seal/lib/schemas/greyseal/v1;greysealv1\xa2\x02\x03SGX\xaa\x02\x13Schemas.Greyseal.V1\xca\x02\x13Schemas\\Greyseal\\V1\xe2\x02\x1fSchemas\\Greyseal\\V1\\GPBMetadata\xea\x02\x15Schemas::Greyseal::V1b\x06proto3"

var (
	file_schemas_greyseal_v1_role_proto_rawDescOnce sync.Once
	file_schemas_greyseal_v1_role_proto_rawDescData []byte
)

func file_schemas_greyseal_v1_role_proto_rawDescGZIP() []byte {
	file_schemas_greyseal_v1_role_proto_rawDescOnce.Do(func() {
		file_schemas_greyseal_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_role_proto_rawDesc), len(file_schemas_greyseal_v1_role_proto_rawDesc)))
	})
	return file_schemas_greyseal_v1_role_proto_rawDescData
}

var file_schemas_greyseal_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schemas_greyseal_v1_role_proto_goTypes = []any{
	(*Role)(nil),                  // 0: schemas.greyseal.v1.Role
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_schemas_greyseal_v1_role_proto_depIdxs = []int32{
	1, // 0: schemas.greyseal.v1.Role.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schemas_greyseal_v1_role_proto_init() }
func file_schemas_greyseal_v1_role_proto_init() {
	if File_schemas_greyseal_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_greyseal_v1_role_proto_rawDesc), len(file_schemas_greyseal_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_greyseal_v1_role_proto_goTypes,
		DependencyIndexes: file_schemas_greyseal_v1_role_proto_depIdxs,
		MessageInfos:      file_schemas_greyseal_v1_role_proto_msgTypes,
	}.Build()
	File_schemas_greyseal_v1_role_proto = out.File
	file_schemas_greyseal_v1_role_proto_goTypes = nil
	file_schemas_greyseal_v1_role_proto_depIdxs = nil
}
